import { SupportType } from "@/dto/support.dto";

export const mockSupport: SupportType = {
    tickets: {
        total: 12,
        new: 2
    },
    average_response_time: {
        time: 2.4,
        response_time: -0.3
    },
    resolution_rate: {
        rate: 94,
        resolution_rate: 2
    },
    critical_issues: {
        total: 3,
        resolved: -1
    },
    support_results: [
        {
            ticket_id: "TICKET-123456",
            subject: "Network Issue",
            tenant: "Pan Pacific",
            status: "open",
            priority: "high",
            assigned: "John Doe",
            created_at: "2024-03-15T08:30:00Z",
            updated_at: "2024-03-15T08:30:00Z",
        },
        {
            ticket_id: "TICKET-123457",
            subject: "Email Not Working",
            tenant: "Grand Hotel",
            status: "open",
            priority: "medium",
            assigned: "Jane Smith",
            created_at: "2024-03-14T10:45:00Z",
            updated_at: "2024-03-14T12:00:00Z",
        },
        {
            ticket_id: "TICKET-123458",
            subject: "Software Installation",
            tenant: "TechCorp",
            status: "open",
            priority: "low",
            assigned: "Mike Johnson",
            created_at: "2024-03-13T14:00:00Z",
            updated_at: "2024-03-13T15:30:00Z",
        },
        {
            ticket_id: "TICKET-123459",
            subject: "Slow Internet",
            tenant: "Greenwood Residences",
            status: "open",
            priority: "high",
            assigned: "Alice Brown",
            created_at: "2024-03-12T09:15:00Z",
            updated_at: "2024-03-12T10:20:00Z",
        },
        {
            ticket_id: "TICKET-123460",
            subject: "Access Denied Issue",
            tenant: "Sunrise Towers",
            status: "open",
            priority: "medium",
            assigned: "Charlie Davis",
            created_at: "2024-03-11T11:45:00Z",
            updated_at: "2024-03-11T12:30:00Z",
        },
        {
            ticket_id: "TICKET-123461",
            subject: "Printer Not Responding",
            tenant: "Blue Sky Offices",
            status: "open",
            priority: "low",
            assigned: "Emma Wilson",
            created_at: "2024-03-10T16:20:00Z",
            updated_at: "2024-03-10T17:00:00Z",
        },
        {
            ticket_id: "TICKET-123462",
            subject: "System Crash",
            tenant: "CloudWorks",
            status: "open",
            priority: "high",
            assigned: "Daniel Lee",
            created_at: "2024-03-09T13:10:00Z",
            updated_at: "2024-03-09T14:45:00Z",
        },
        {
            ticket_id: "TICKET-123463",
            subject: "VPN Connection Issues",
            tenant: "SecureNet",
            status: "open",
            priority: "medium",
            assigned: "Sophia Martinez",
            created_at: "2024-03-08T07:50:00Z",
            updated_at: "2024-03-08T09:00:00Z",
        },
        {
            ticket_id: "TICKET-123464",
            subject: "Website Downtime",
            tenant: "E-Shop Inc.",
            status: "open",
            priority: "high",
            assigned: "Liam Anderson",
            created_at: "2024-03-07T22:30:00Z",
            updated_at: "2024-03-07T23:45:00Z",
        },
        {
            ticket_id: "TICKET-123465",
            subject: "Mobile App Bug",
            tenant: "FinTech Solutions",
            status: "open",
            priority: "medium",
            assigned: "Olivia Taylor",
            created_at: "2024-03-06T15:40:00Z",
            updated_at: "2024-03-06T16:50:00Z",
        },
        {
            ticket_id: "TICKET-123466",
            subject: "Database Backup Failed",
            tenant: "DataGuard",
            status: "open",
            priority: "high",
            assigned: "Noah Harris",
            created_at: "2024-03-05T04:25:00Z",
            updated_at: "2024-03-05T05:30:00Z",
        },
        {
            ticket_id: "TICKET-123467",
            subject: "Login Issue",
            tenant: "CorpSys",
            status: "open",
            priority: "low",
            assigned: "Isabella Walker",
            created_at: "2024-03-04T18:10:00Z",
            updated_at: "2024-03-04T19:20:00Z",
        },
        {
            ticket_id: "TICKET-123468",
            subject: "Server Overload",
            tenant: "MegaCloud",
            status: "open",
            priority: "high",
            assigned: "William Scott",
            created_at: "2025-03-06T09:00:00Z",
            updated_at: "2025-03-06T09:15:00Z",
        },
        {
            ticket_id: "TICKET-123469",
            subject: "Email Synchronization Issue",
            tenant: "EnterpriseX",
            status: "open",
            priority: "medium",
            assigned: "Ava King",
            created_at: "2025-03-06T11:45:00Z",
            updated_at: "2025-03-06T12:00:00Z",
        },
    ],
}