type CurrencyConfigDto = {
    code: string;
    name: string;
    country: string;
    symbol: string;
};

const currenciesIso: CurrencyConfigDto[] = [
    { code: "AED", name: "UAE Dirham", country: "United Arab Emirates", symbol: "د.إ" },
    { code: "AFN", name: "Afghan Afghani", country: "Afghanistan", symbol: "؋" },
    { code: "ALL", name: "Albanian Lek", country: "Albania", symbol: "L" },
    { code: "AMD", name: "Armenian Dram", country: "Armenia", symbol: "֏" },
    { code: "ANG", name: "Netherlands Antillean Guilder", country: "Netherlands Antilles", symbol: "ƒ" },
    { code: "AOA", name: "Angolan Kwanza", country: "Angola", symbol: "Kz" },
    { code: "ARS", name: "Argentine Peso", country: "Argentina", symbol: "$" },
    { code: "AUD", name: "Australian Dollar", country: "Australia", symbol: "A$" },
    { code: "AWG", name: "Aruban Florin", country: "Aruba", symbol: "ƒ" },
    { code: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan", symbol: "₼" },
    { code: "BAM", name: "Bosnia and Herzegovina Mark", country: "Bosnia and Herzegovina", symbol: "KM" },
    { code: "BBD", name: "Barbados Dollar", country: "Barbados", symbol: "Bds$" },
    { code: "BDT", name: "Bangladeshi Taka", country: "Bangladesh", symbol: "৳" },
    { code: "BGN", name: "Bulgarian Lev", country: "Bulgaria", symbol: "лв" },
    { code: "BHD", name: "Bahraini Dinar", country: "Bahrain", symbol: ".د.ب" },
    { code: "BIF", name: "Burundian Franc", country: "Burundi", symbol: "FBu" },
    { code: "BMD", name: "Bermudian Dollar", country: "Bermuda", symbol: "$" },
    { code: "BND", name: "Brunei Dollar", country: "Brunei", symbol: "B$" },
    { code: "BOB", name: "Bolivian Boliviano", country: "Bolivia", symbol: "Bs." },
    { code: "BRL", name: "Brazilian Real", country: "Brazil", symbol: "R$" },
    { code: "BSD", name: "Bahamian Dollar", country: "Bahamas", symbol: "B$" },
    { code: "BTN", name: "Bhutanese Ngultrum", country: "Bhutan", symbol: "Nu." },
    { code: "BWP", name: "Botswana Pula", country: "Botswana", symbol: "P" },
    { code: "BYN", name: "Belarusian Ruble", country: "Belarus", symbol: "Br" },
    { code: "BZD", name: "Belize Dollar", country: "Belize", symbol: "BZ$" },
    { code: "CAD", name: "Canadian Dollar", country: "Canada", symbol: "CA$" },
    { code: "CDF", name: "Congolese Franc", country: "Democratic Republic of the Congo", symbol: "FC" },
    { code: "CHF", name: "Swiss Franc", country: "Switzerland", symbol: "CHF" },
    { code: "CLP", name: "Chilean Peso", country: "Chile", symbol: "CLP$" },
    { code: "CNY", name: "Chinese Yuan", country: "China", symbol: "¥" },
    { code: "COP", name: "Colombian Peso", country: "Colombia", symbol: "COL$" },
    { code: "CRC", name: "Costa Rican Colón", country: "Costa Rica", symbol: "₡" },
    { code: "CUP", name: "Cuban Peso", country: "Cuba", symbol: "₱" },
    { code: "CVE", name: "Cape Verdean Escudo", country: "Cape Verde", symbol: "$" },
    { code: "CZK", name: "Czech Koruna", country: "Czech Republic", symbol: "Kč" },
    { code: "DJF", name: "Djiboutian Franc", country: "Djibouti", symbol: "Fdj" },
    { code: "DKK", name: "Danish Krone", country: "Denmark", symbol: "kr" },
    { code: "DOP", name: "Dominican Peso", country: "Dominican Republic", symbol: "RD$" },
    { code: "DZD", name: "Algerian Dinar", country: "Algeria", symbol: "دج" },
    { code: "EGP", name: "Egyptian Pound", country: "Egypt", symbol: "£" },
    { code: "ERN", name: "Eritrean Nakfa", country: "Eritrea", symbol: "Nfk" },
    { code: "ETB", name: "Ethiopian Birr", country: "Ethiopia", symbol: "Br" },
    { code: "EUR", name: "Euro", country: "European Union", symbol: "€" },
    { code: "FJD", name: "Fijian Dollar", country: "Fiji", symbol: "FJ$" },
    { code: "FKP", name: "Falkland Islands Pound", country: "Falkland Islands", symbol: "£" },
    { code: "FOK", name: "Faroese Króna", country: "Faroe Islands", symbol: "kr" },
    { code: "GBP", name: "Pound Sterling", country: "United Kingdom", symbol: "£" },
    { code: "GEL", name: "Georgian Lari", country: "Georgia", symbol: "₾" },
    { code: "GGP", name: "Guernsey Pound", country: "Guernsey", symbol: "£" },
    { code: "GHS", name: "Ghanaian Cedi", country: "Ghana", symbol: "GH₵" },
    { code: "GIP", name: "Gibraltar Pound", country: "Gibraltar", symbol: "£" },
    { code: "GMD", name: "Gambian Dalasi", country: "The Gambia", symbol: "D" },
    { code: "GNF", name: "Guinean Franc", country: "Guinea", symbol: "FG" },
    { code: "GTQ", name: "Guatemalan Quetzal", country: "Guatemala", symbol: "Q" },
    { code: "GYD", name: "Guyanese Dollar", country: "Guyana", symbol: "G$" },
    { code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong", symbol: "HK$" },
    { code: "HNL", name: "Honduran Lempira", country: "Honduras", symbol: "L" },
    { code: "HRK", name: "Croatian Kuna", country: "Croatia", symbol: "kn" },
    { code: "HTG", name: "Haitian Gourde", country: "Haiti", symbol: "G" },
    { code: "HUF", name: "Hungarian Forint", country: "Hungary", symbol: "Ft" },
    { code: "IDR", name: "Indonesian Rupiah", country: "Indonesia", symbol: "Rp" },
    { code: "ILS", name: "Israeli New Shekel", country: "Israel", symbol: "₪" },
    { code: "IMP", name: "Manx Pound", country: "Isle of Man", symbol: "£" },
    { code: "INR", name: "Indian Rupee", country: "India", symbol: "₹" },
    { code: "IQD", name: "Iraqi Dinar", country: "Iraq", symbol: "ع.د" },
    { code: "IRR", name: "Iranian Rial", country: "Iran", symbol: "﷼" },
    { code: "ISK", name: "Icelandic Króna", country: "Iceland", symbol: "kr" },
    { code: "JEP", name: "Jersey Pound", country: "Jersey", symbol: "£" },
    { code: "JMD", name: "Jamaican Dollar", country: "Jamaica", symbol: "J$" },
    { code: "JOD", name: "Jordanian Dinar", country: "Jordan", symbol: "JD" },
    { code: "JPY", name: "Japanese Yen", country: "Japan", symbol: "¥" },
    { code: "KES", name: "Kenyan Shilling", country: "Kenya", symbol: "KSh" },
    { code: "KGS", name: "Kyrgyzstani Som", country: "Kyrgyzstan", symbol: "с" },
    { code: "KHR", name: "Cambodian Riel", country: "Cambodia", symbol: "៛" },
    { code: "KID", name: "Kiribati Dollar", country: "Kiribati", symbol: "$" },
    { code: "KMF", name: "Comorian Franc", country: "Comoros", symbol: "CF" },
    { code: "KPW", name: "North Korean Won", country: "North Korea", symbol: "₩" },
    { code: "KRW", name: "South Korean Won", country: "South Korea", symbol: "₩" },
    { code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait", symbol: "د.ك" },
    { code: "KYD", name: "Cayman Islands Dollar", country: "Cayman Islands", symbol: "CI$" },
    { code: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan", symbol: "₸" },
    { code: "LAK", name: "Lao Kip", country: "Laos", symbol: "₭" },
    { code: "LBP", name: "Lebanese Pound", country: "Lebanon", symbol: "ل.ل" },
    { code: "LKR", name: "Sri Lankan Rupee", country: "Sri Lanka", symbol: "₨" },
    { code: "LRD", name: "Liberian Dollar", country: "Liberia", symbol: "L$" },
    { code: "LSL", name: "Lesotho Loti", country: "Lesotho", symbol: "L" },
    { code: "LYD", name: "Libyan Dinar", country: "Libya", symbol: "د.ل" },
    { code: "MAD", name: "Moroccan Dirham", country: "Morocco", symbol: "د.م." },
    { code: "MDL", name: "Moldovan Leu", country: "Moldova", symbol: "L" },
    { code: "MGA", name: "Malagasy Ariary", country: "Madagascar", symbol: "Ar" },
    { code: "MKD", name: "Macedonian Denar", country: "North Macedonia", symbol: "ден" },
    { code: "MMK", name: "Myanma Kyat", country: "Myanmar", symbol: "K" },
    { code: "MNT", name: "Mongolian Tugrik", country: "Mongolia", symbol: "₮" },
    { code: "MOP", name: "Macanese Pataca", country: "Macau", symbol: "MOP$" },
    { code: "MRU", name: "Mauritanian Ouguiya", country: "Mauritania", symbol: "UM" },
    { code: "MUR", name: "Mauritian Rupee", country: "Mauritius", symbol: "₨" },
    { code: "MVR", name: "Maldivian Rufiyaa", country: "Maldives", symbol: "ރ" },
    { code: "MWK", name: "Malawian Kwacha", country: "Malawi", symbol: "MK" },
    { code: "MXN", name: "Mexican Peso", country: "Mexico", symbol: "MX$" },
    { code: "MYR", name: "Malaysian Ringgit", country: "Malaysia", symbol: "RM" },
    { code: "MZN", name: "Mozambican Metical", country: "Mozambique", symbol: "MT" },
    { code: "NAD", name: "Namibian Dollar", country: "Namibia", symbol: "N$" },
    { code: "NGN", name: "Nigerian Naira", country: "Nigeria", symbol: "₦" },
    { code: "NIO", name: "Nicaraguan Córdoba", country: "Nicaragua", symbol: "C$" },
    { code: "NOK", name: "Norwegian Krone", country: "Norway", symbol: "kr" },
    { code: "NPR", name: "Nepalese Rupee", country: "Nepal", symbol: "₨" },
    { code: "NZD", name: "New Zealand Dollar", country: "New Zealand", symbol: "NZ$" },
    { code: "OMR", name: "Omani Rial", country: "Oman", symbol: "ر.ع." },
    { code: "PAB", name: "Panamanian Balboa", country: "Panama", symbol: "B/." },
    { code: "PEN", name: "Peruvian Sol", country: "Peru", symbol: "S/" },
    { code: "PGK", name: "Papua New Guinean Kina", country: "Papua New Guinea", symbol: "K" },
    { code: "PHP", name: "Philippine Peso", country: "Philippines", symbol: "₱" },
    { code: "PKR", name: "Pakistani Rupee", country: "Pakistan", symbol: "₨" },
    { code: "PLN", name: "Polish Zloty", country: "Poland", symbol: "zł" },
    { code: "PYG", name: "Paraguayan Guaraní", country: "Paraguay", symbol: "₲" },
    { code: "QAR", name: "Qatari Rial", country: "Qatar", symbol: "ر.ق" },
    { code: "RON", name: "Romanian Leu", country: "Romania", symbol: "lei" },
    { code: "RSD", name: "Serbian Dinar", country: "Serbia", symbol: "дин" },
    { code: "RUB", name: "Russian Ruble", country: "Russia", symbol: "₽" },
    { code: "RWF", name: "Rwandan Franc", country: "Rwanda", symbol: "FRw" },
    { code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia", symbol: "ر.س" },
    { code: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands", symbol: "SI$" },
    { code: "SCR", name: "Seychellois Rupee", country: "Seychelles", symbol: "₨" },
    { code: "SDG", name: "Sudanese Pound", country: "Sudan", symbol: "£" },
    { code: "SEK", name: "Swedish Krona", country: "Sweden", symbol: "kr" },
    { code: "SGD", name: "Singapore Dollar", country: "Singapore", symbol: "S$" },
    { code: "SHP", name: "Saint Helena Pound", country: "Saint Helena", symbol: "£" },
    { code: "SLL", name: "Sierra Leonean Leone", country: "Sierra Leone", symbol: "Le" },
    { code: "SOS", name: "Somali Shilling", country: "Somalia", symbol: "Sh.so." },
    { code: "SRD", name: "Surinamese Dollar", country: "Suriname", symbol: "SRD$" },
    { code: "SSP", name: "South Sudanese Pound", country: "South Sudan", symbol: "£" },
    { code: "STN", name: "São Tomé and Príncipe Dobra", country: "São Tomé and Príncipe", symbol: "Db" },
    { code: "SYP", name: "Syrian Pound", country: "Syria", symbol: "ل.س" },
    { code: "SZL", name: "Swazi Lilangeni", country: "Swaziland", symbol: "L" },
    { code: "THB", name: "Thai Baht", country: "Thailand", symbol: "฿" },
    { code: "TJS", name: "Tajikistani Somoni", country: "Tajikistan", symbol: "ЅМ" },
    { code: "TMT", name: "Turkmenistan Manat", country: "Turkmenistan", symbol: "₴" },
    { code: "TND", name: "Tunisian Dinar", country: "Tunisia", symbol: "د.ت" },
    { code: "TOP", name: "Tongan Pa'anga", country: "Tonga", symbol: "T$" },
    { code: "TRY", name: "Turkish Lira", country: "Turkey", symbol: "₺" },
    { code: "TTD", name: "Trinidad and Tobago Dollar", country: "Trinidad and Tobago", symbol: "TT$" },
    { code: "TWD", name: "New Taiwan Dollar", country: "Taiwan", symbol: "NT$" },
    { code: "TZS", name: "Tanzanian Shilling", country: "Tanzania", symbol: "Sh" },
    { code: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine", symbol: "₴" },
    { code: "UGX", name: "Ugandan Shilling", country: "Uganda", symbol: "USh" },
    { code: "USD", name: "United States Dollar", country: "United States", symbol: "$" },
    { code: "UYU", name: "Uruguayan Peso", country: "Uruguay", symbol: "$U" },
    { code: "UZS", name: "Uzbekistani Som", country: "Uzbekistan", symbol: "лв" },
];

export default currenciesIso;
