import { AccountCodeMappingDto } from "@/dtos/finance.dto";

export const mockAccountCodeMappingData: AccountCodeMappingDto[] = [
    {
        id: "acm-1",
        location: "New York Warehouse",
        category: "Office Supplies",
        sub_category: "Stationery",
        item_group: "Paper Products",
        department_count: 5,
        account_code: "ACC-1001",
    },
    {
        id: "acm-2",
        location: "Los Angeles Distribution",
        category: "Office Supplies",
        sub_category: "Furniture",
        item_group: "Desks & Chairs",
        department_count: 3,
        account_code: "ACC-1002",
    },
    {
        id: "acm-3",
        location: "Chicago HQ",
        category: "IT Equipment",
        sub_category: "Computers",
        item_group: "Laptops",
        department_count: 7,
        account_code: "ACC-2001",
    },
    {
        id: "acm-4",
        location: "Houston Warehouse",
        category: "IT Equipment",
        sub_category: "Accessories",
        item_group: "Keyboards & Mice",
        department_count: 4,
        account_code: "ACC-2002",
    },
    {
        id: "acm-5",
        location: "San Francisco Office",
        category: "Facilities",
        sub_category: "Cleaning Supplies",
        item_group: "Detergents",
        department_count: 6,
        account_code: "ACC-3001",
    },
    {
        id: "acm-6",
        location: "Dallas Branch",
        category: "Facilities",
        sub_category: "Security",
        item_group: "CCTV & Alarms",
        department_count: 2,
        account_code: "ACC-3002",
    },
    {
        id: "acm-7",
        location: "Seattle Office",
        category: "Logistics",
        sub_category: "Packaging",
        item_group: "Boxes & Tape",
        department_count: 8,
        account_code: "ACC-4001",
    },
    {
        id: "acm-8",
        location: "Boston HQ",
        category: "Logistics",
        sub_category: "Fleet Maintenance",
        item_group: "Vehicle Parts",
        department_count: 5,
        account_code: "ACC-4002",
    },
    {
        id: "acm-9",
        location: "Miami Warehouse",
        category: "HR & Training",
        sub_category: "Employee Benefits",
        item_group: "Gym Memberships",
        department_count: 3,
        account_code: "ACC-5001",
    },
    {
        id: "acm-10",
        location: "Denver Distribution",
        category: "HR & Training",
        sub_category: "Workshops",
        item_group: "Leadership Training",
        department_count: 4,
        account_code: "ACC-5002",
    },
];