import {
  InventoryAdjustmentDTO,
  PeriodEndDto,
  PhysicalCountDto,
  SpotCheckDto,
  StockCardDto,
} from "@/dtos/inventory-management.dto";

export const mockInventoryAdjustments: InventoryAdjustmentDTO[] = [
  {
    id: "IA-001",
    adj_no: "ADJ-20240301-001",
    adj_date: "2024-03-01",
    type: "IN",
    location: "Main Warehouse",
    reason: "New stock received",
    item_count: 150,
    status: "Completed",
    total_value: 50000,
  },
  {
    id: "IA-002",
    adj_no: "ADJ-20240302-002",
    adj_date: "2024-03-02",
    type: "OUT",
    location: "Branch A",
    reason: "Damaged items",
    item_count: 20,
    status: "Pending",
    total_value: 8000,
  },
  {
    id: "IA-003",
    adj_no: "ADJ-20240303-003",
    adj_date: "2024-03-03",
    type: "IN",
    location: "Branch B",
    reason: "Reallocation of goods",
    item_count: 50,
    status: "Approved",
    total_value: 15000,
  },
  {
    id: "IA-004",
    adj_no: "ADJ-20240304-004",
    adj_date: "2024-03-04",
    type: "OUT",
    location: "Main Warehouse",
    reason: "Expired products",
    item_count: 30,
    status: "Rejected",
    total_value: 12000,
  },
  {
    id: "IA-005",
    adj_no: "ADJ-20240305-005",
    adj_date: "2024-03-05",
    type: "IN",
    location: "Branch C",
    reason: "Supplier return",
    item_count: 40,
    status: "Completed",
    total_value: 20000,
  },
  {
    id: "IA-006",
    adj_no: "ADJ-20240306-006",
    adj_date: "2024-03-06",
    type: "OUT",
    location: "Branch D",
    reason: "Inventory shrinkage",
    item_count: 25,
    status: "Pending",
    total_value: 10000,
  },
  {
    id: "IA-007",
    adj_no: "ADJ-20240307-007",
    adj_date: "2024-03-07",
    type: "IN",
    location: "Main Warehouse",
    reason: "Redistribution to other branches",
    item_count: 60,
    status: "Approved",
    total_value: 24000,
  },
  {
    id: "IA-008",
    adj_no: "ADJ-20240308-008",
    adj_date: "2024-03-08",
    type: "IN",
    location: "Branch E",
    reason: "Miscount correction",
    item_count: 35,
    status: "Completed",
    total_value: 14000,
  },
  {
    id: "IA-009",
    adj_no: "ADJ-20240309-009",
    adj_date: "2024-03-09",
    type: "OUT",
    location: "Branch F",
    reason: "Lost items",
    item_count: 10,
    status: "Rejected",
    total_value: 4000,
  },
  {
    id: "IA-010",
    adj_no: "ADJ-20240310-010",
    adj_date: "2024-03-10",
    type: "IN",
    location: "Main Warehouse",
    reason: "Found missing items",
    item_count: 55,
    status: "Approved",
    total_value: 22000,
  },
];

export const mockPeriodEndData: PeriodEndDto[] = [
  {
    id: "PE-001",
    pe_no: "PE-202401",
    pe_date: "2024-01-31",
    start_date: "2024-01-01",
    end_date: "2024-01-31",
    status: "Completed",
    created_by: "admin",
    completed_at: "2024-02-01 10:00:00",
    note: "Period closed successfully",
  },
  {
    id: "PE-002",
    pe_no: "PE-202402",
    pe_date: "2024-02-29",
    start_date: "2024-02-01",
    end_date: "2024-02-29",
    status: "Completed",
    created_by: "admin",
    completed_at: "2024-03-01 10:30:00",
    note: "No discrepancies found",
  },
  {
    id: "PE-003",
    pe_no: "PE-202403",
    pe_date: "2024-03-31",
    start_date: "2024-03-01",
    end_date: "2024-03-31",
    status: "In Progress",
    created_by: "finance_manager",
    completed_at: "",
    note: "Pending approval",
  },
  {
    id: "PE-004",
    pe_no: "PE-202404",
    pe_date: "2024-04-30",
    start_date: "2024-04-01",
    end_date: "2024-04-30",
    status: "Pending",
    created_by: "finance_team",
    completed_at: "",
    note: "Awaiting data validation",
  },
  {
    id: "PE-005",
    pe_no: "PE-202305",
    pe_date: "2023-05-31",
    start_date: "2023-05-01",
    end_date: "2023-05-31",
    status: "Completed",
    created_by: "admin",
    completed_at: "2023-06-01 09:45:00",
    note: "Successfully closed",
  },
  {
    id: "PE-006",
    pe_no: "PE-202306",
    pe_date: "2023-06-30",
    start_date: "2023-06-01",
    end_date: "2023-06-30",
    status: "Completed",
    created_by: "admin",
    completed_at: "2023-07-01 08:30:00",
    note: "No outstanding issues",
  },
  {
    id: "PE-007",
    pe_no: "PE-202307",
    pe_date: "2023-07-31",
    start_date: "2023-07-01",
    end_date: "2023-07-31",
    status: "Completed",
    created_by: "finance_manager",
    completed_at: "2023-08-01 11:15:00",
    note: "Reviewed and closed",
  },
  {
    id: "PE-008",
    pe_no: "PE-202308",
    pe_date: "2023-08-31",
    start_date: "2023-08-01",
    end_date: "2023-08-31",
    status: "Completed",
    created_by: "admin",
    completed_at: "2023-09-01 10:50:00",
    note: "All accounts reconciled",
  },
  {
    id: "PE-009",
    pe_no: "PE-202309",
    pe_date: "2023-09-30",
    start_date: "2023-09-01",
    end_date: "2023-09-30",
    status: "Rejected",
    created_by: "finance_team",
    completed_at: "",
    note: "Errors found in ledger",
  },
  {
    id: "PE-010",
    pe_no: "PE-202310",
    pe_date: "2023-10-31",
    start_date: "2023-10-01",
    end_date: "2023-10-31",
    status: "Completed",
    created_by: "admin",
    completed_at: "2023-11-01 09:30:00",
    note: "Final review completed",
  },
];

export const mockDepartments = [
  { id: "1", name: "F&B" },
  { id: "2", name: "Housekeeping" },
  { id: "3", name: "Maintenance" },
  { id: "4", name: "Front Office" },
  { id: "5", name: "Security" },
];

export const mockStoreLocations = [
  { id: "1", name: "Main Kitchen Store" },
  { id: "2", name: "Dry Store" },
  { id: "3", name: "Cold Room" },
  { id: "4", name: "Linen Room" },
  { id: "5", name: "Equipment Store" },
];

export const mockSpotCheckData: SpotCheckDto[] = [
  {
    id: "SC-001",
    department: "Finance",
    status: "Completed",
    location: "Main Kitchen Store",
    requested_by: "John Doe",
    date: "2024-07-01",
    checked_items: 48,
    count_items: 50,
  },
  {
    id: "SC-002",
    department: "Warehouse",
    status: "Pending",
    location: "Dry Store",
    requested_by: "Jane Smith",
    date: "2024-07-05",
    checked_items: 0,
    count_items: 30,
  },
  {
    id: "SC-003",
    department: "IT",
    status: "In Progress",
    location: "Cold Room",
    requested_by: "Alice Brown",
    date: "2024-07-10",
    checked_items: 12,
    count_items: 20,
  },
  {
    id: "SC-004",
    department: "Logistics",
    status: "Completed",
    location: "Linen Room",
    requested_by: "Bob Johnson",
    date: "2024-07-12",
    checked_items: 60,
    count_items: 60,
  },
  {
    id: "SC-005",
    department: "Procurement",
    status: "Rejected",
    location: "Equipment Store",
    requested_by: "Charlie Wilson",
    date: "2024-07-15",
    checked_items: 25,
    count_items: 40,
  },
  {
    id: "SC-006",
    department: "HR",
    status: "Pending",
    location: "Main Kitchen Store",
    requested_by: "Daniel Lee",
    date: "2024-07-18",
    checked_items: 0,
    count_items: 10,
  },
  {
    id: "SC-007",
    department: "Marketing",
    status: "Completed",
    location: "Main Kitchen Store",
    requested_by: "Emma White",
    date: "2024-07-20",
    checked_items: 30,
    count_items: 30,
  },
  {
    id: "SC-008",
    department: "Production",
    status: "In Progress",
    location: "Dry Store",
    requested_by: "George Harris",
    date: "2024-07-22",
    checked_items: 15,
    count_items: 25,
  },
  {
    id: "SC-009",
    department: "Quality Control",
    status: "Completed",
    location: "Cold Room",
    requested_by: "Hannah Clark",
    date: "2024-07-25",
    checked_items: 50,
    count_items: 50,
  },
  {
    id: "SC-010",
    department: "Maintenance",
    status: "Rejected",
    location: "Equipment Store",
    requested_by: "Ian Miller",
    date: "2024-07-28",
    checked_items: 22,
    count_items: 30,
  },
];

export const mockPhysicalCountData: PhysicalCountDto[] = [
  {
    id: "PC-001",
    department: "Warehouse",
    location: "A1",
    status: "Completed",
    requested_by: "John Doe",
    date: "2024-07-01",
    checked_items: 48,
    count_items: 50,
  },
  {
    id: "PC-002",
    department: "Finance",
    location: "B3",
    status: "Pending",
    requested_by: "Jane Smith",
    date: "2024-07-05",
    checked_items: 0,
    count_items: 30,
  },
  {
    id: "PC-003",
    department: "IT",
    location: "C2",
    status: "In Progress",
    requested_by: "Alice Brown",
    date: "2024-07-10",
    checked_items: 12,
    count_items: 20,
  },
  {
    id: "PC-004",
    department: "Logistics",
    location: "D5",
    status: "Completed",
    requested_by: "Bob Johnson",
    date: "2024-07-12",
    checked_items: 60,
    count_items: 60,
  },
  {
    id: "PC-005",
    department: "Procurement",
    location: "E1",
    status: "Rejected",
    requested_by: "Charlie Wilson",
    date: "2024-07-15",
    checked_items: 25,
    count_items: 40,
  },
  {
    id: "PC-006",
    department: "HR",
    location: "F3",
    status: "Pending",
    requested_by: "Daniel Lee",
    date: "2024-07-18",
    checked_items: 0,
    count_items: 10,
  },
  {
    id: "PC-007",
    department: "Marketing",
    location: "G2",
    status: "Completed",
    requested_by: "Emma White",
    date: "2024-07-20",
    checked_items: 30,
    count_items: 30,
  },
  {
    id: "PC-008",
    department: "Production",
    location: "H4",
    status: "In Progress",
    requested_by: "George Harris",
    date: "2024-07-22",
    checked_items: 15,
    count_items: 25,
  },
  {
    id: "PC-009",
    department: "Quality Control",
    location: "I5",
    status: "Completed",
    requested_by: "Hannah Clark",
    date: "2024-07-25",
    checked_items: 50,
    count_items: 50,
  },
  {
    id: "PC-010",
    department: "Maintenance",
    location: "J3",
    status: "Rejected",
    requested_by: "Ian Miller",
    date: "2024-07-28",
    checked_items: 22,
    count_items: 30,
  },
];

export const mockStockCardData: StockCardDto[] = [
  {
    id: "SC-001",
    code: "STK1001",
    name: "Laptop Dell XPS 13",
    category: "Electronics",
    status: true,
    count: 5,
    unit: "pcs",
    stock_level: "low",
    value: 50000,
  },
  {
    id: "SC-002",
    code: "STK1002",
    name: "Wireless Mouse",
    category: "Accessories",
    status: true,
    count: 20,
    unit: "pcs",
    stock_level: "medium",
    value: 4000,
  },
  {
    id: "SC-003",
    code: "STK1003",
    name: "Office Chair",
    category: "Furniture",
    status: true,
    count: 50,
    unit: "pcs",
    stock_level: "high",
    value: 25000,
  },
  {
    id: "SC-004",
    code: "STK1004",
    name: "LED Monitor 24-inch",
    category: "Electronics",
    status: false,
    count: 3,
    unit: "pcs",
    stock_level: "low",
    value: 12000,
  },
  {
    id: "SC-005",
    code: "STK1005",
    name: "Mechanical Keyboard",
    category: "Accessories",
    status: true,
    count: 15,
    unit: "pcs",
    stock_level: "medium",
    value: 7500,
  },
  {
    id: "SC-006",
    code: "STK1006",
    name: "Printer Ink Cartridge",
    category: "Office Supplies",
    status: false,
    count: 8,
    unit: "pcs",
    stock_level: "low",
    value: 3000,
  },
  {
    id: "SC-007",
    code: "STK1007",
    name: "External Hard Drive 1TB",
    category: "Storage",
    status: true,
    count: 30,
    unit: "pcs",
    stock_level: "high",
    value: 45000,
  },
  {
    id: "SC-008",
    code: "STK1008",
    name: "USB-C Docking Station",
    category: "Accessories",
    status: true,
    count: 12,
    unit: "pcs",
    stock_level: "medium",
    value: 18000,
  },
  {
    id: "SC-009",
    code: "STK1009",
    name: "Ergonomic Desk",
    category: "Furniture",
    status: true,
    count: 7,
    unit: "pcs",
    stock_level: "low",
    value: 35000,
  },
  {
    id: "SC-010",
    code: "STK1010",
    name: "Smartphone Samsung Galaxy S24",
    category: "Electronics",
    status: true,
    count: 25,
    unit: "pcs",
    stock_level: "high",
    value: 100000,
  },
];
