import { CategoryRecipeDto, CuisineTypeDto } from "@/dtos/operational-planning.dto";

export const mockCuisineTypeData: CuisineTypeDto[] = [
    {
        id: "CT-001",
        name: "Japanese",
        code: "JP-CUISINE",
        description: "Traditional Japanese dishes with sushi, ramen, and tempura.",
        region: "East Asia",
        status: "active",
        recipe_count: 120,
        active_count: 95,
        last_active: "2024-07-10",
    },
    {
        id: "CT-002",
        name: "Italian",
        code: "IT-CUISINE",
        description: "Famous for pasta, pizza, and rich sauces.",
        region: "Europe",
        status: "active",
        recipe_count: 180,
        active_count: 150,
        last_active: "2024-06-30",
    },
    {
        id: "CT-003",
        name: "Mexican",
        code: "MX-CUISINE",
        description: "Spicy dishes featuring tacos, enchiladas, and tamales.",
        region: "Latin America",
        status: "active",
        recipe_count: 95,
        active_count: 80,
        last_active: "2024-07-15",
    },
    {
        id: "CT-004",
        name: "Thai",
        code: "TH-CUISINE",
        description: "Balance of sweet, sour, spicy, and savory flavors with curries and stir-fries.",
        region: "Southeast Asia",
        status: "active",
        recipe_count: 130,
        active_count: 110,
        last_active: "2024-07-12",
    },
    {
        id: "CT-005",
        name: "Indian",
        code: "IN-CUISINE",
        description: "Richly spiced curries, biryanis, and naan bread.",
        region: "South Asia",
        status: "inactive",
        recipe_count: 200,
        active_count: 175,
        last_active: "2024-05-22",
    },
    {
        id: "CT-006",
        name: "French",
        code: "FR-CUISINE",
        description: "Elegant dishes including croissants, coq au vin, and soufflés.",
        region: "Europe",
        status: "active",
        recipe_count: 160,
        active_count: 140,
        last_active: "2024-06-20",
    },
    {
        id: "CT-007",
        name: "Korean",
        code: "KR-CUISINE",
        description: "Kimchi, bibimbap, and Korean BBQ with bold flavors.",
        region: "East Asia",
        status: "active",
        recipe_count: 110,
        active_count: 90,
        last_active: "2024-07-08",
    },
    {
        id: "CT-008",
        name: "Mediterranean",
        code: "MED-CUISINE",
        description: "Healthy diet based on olive oil, fresh vegetables, and seafood.",
        region: "Mediterranean",
        status: "inactive",
        recipe_count: 140,
        active_count: 115,
        last_active: "2024-06-10",
    },
    {
        id: "CT-009",
        name: "American",
        code: "US-CUISINE",
        description: "Burgers, BBQ, and fast food staples.",
        region: "North America",
        status: "active",
        recipe_count: 90,
        active_count: 75,
        last_active: "2024-07-05",
    },
    {
        id: "CT-010",
        name: "Middle Eastern",
        code: "ME-CUISINE",
        description: "Dishes rich in spices, including hummus, kebabs, and falafel.",
        region: "Middle East",
        status: "active",
        recipe_count: 125,
        active_count: 100,
        last_active: "2024-07-14",
    },
];

export const mockCategoryRecipeData: CategoryRecipeDto[] = [
    {
        id: "CR-001",
        name: "Appetizers",
        code: "APPETIZERS",
        description: "Small dishes served before the main course.",
        status: "active",
        recipe_count: 50,
        active_count: 45,
        last_active: "2024-07-15",
        avg_cost: 3.5,
        avg_margin: 40,
        last_update: "2024-07-20",
    },
    {
        id: "CR-002",
        name: "Main Courses",
        code: "MAIN-COURSES",
        description: "Hearty dishes that serve as the primary meal.",
        status: "active",
        recipe_count: 120,
        active_count: 110,
        last_active: "2024-07-18",
        avg_cost: 10.0,
        avg_margin: 35,
        last_update: "2024-07-21",
    },
    {
        id: "CR-003",
        name: "Desserts",
        code: "DESSERTS",
        description: "Sweet dishes typically served at the end of a meal.",
        status: "active",
        recipe_count: 80,
        active_count: 75,
        last_active: "2024-07-16",
        avg_cost: 4.5,
        avg_margin: 50,
        last_update: "2024-07-19",
    },
    {
        id: "CR-004",
        name: "Beverages",
        code: "BEVERAGES",
        description: "Drinks including juices, smoothies, and cocktails.",
        status: "active",
        recipe_count: 60,
        active_count: 55,
        last_active: "2024-07-14",
        avg_cost: 2.0,
        avg_margin: 60,
        last_update: "2024-07-18",
    },
    {
        id: "CR-005",
        name: "Salads",
        code: "SALADS",
        description: "Fresh vegetable and protein-based salads.",
        status: "active",
        recipe_count: 40,
        active_count: 38,
        last_active: "2024-07-13",
        avg_cost: 5.0,
        avg_margin: 45,
        last_update: "2024-07-17",
    },
    {
        id: "CR-006",
        name: "Seafood",
        code: "SEAFOOD",
        description: "Dishes primarily featuring fish and shellfish.",
        status: "active",
        recipe_count: 70,
        active_count: 65,
        last_active: "2024-07-12",
        avg_cost: 12.0,
        avg_margin: 30,
        last_update: "2024-07-16",
    },
    {
        id: "CR-007",
        name: "Vegetarian",
        code: "VEGETARIAN",
        description: "Dishes made without meat or seafood.",
        status: "active",
        recipe_count: 55,
        active_count: 50,
        last_active: "2024-07-11",
        avg_cost: 6.5,
        avg_margin: 42,
        last_update: "2024-07-15",
    },
    {
        id: "CR-008",
        name: "Soups",
        code: "SOUPS",
        description: "Warm and comforting broth-based dishes.",
        status: "active",
        recipe_count: 30,
        active_count: 28,
        last_active: "2024-07-10",
        avg_cost: 3.0,
        avg_margin: 55,
        last_update: "2024-07-14",
    },
    {
        id: "CR-009",
        name: "Grilled",
        code: "GRILLED",
        description: "Dishes cooked over an open flame or grill.",
        status: "active",
        recipe_count: 45,
        active_count: 40,
        last_active: "2024-07-09",
        avg_cost: 8.0,
        avg_margin: 38,
        last_update: "2024-07-13",
    },
    {
        id: "CR-010",
        name: "Fast Food",
        code: "FAST-FOOD",
        description: "Quick meals including burgers, fries, and fried chicken.",
        status: "active",
        recipe_count: 90,
        active_count: 85,
        last_active: "2024-07-08",
        avg_cost: 5.5,
        avg_margin: 48,
        last_update: "2024-07-12",
    },
];