import { CuisineTypeDto } from "@/dtos/operational-planning.dto";

export const mockCuisineTypeData: CuisineTypeDto[] = [
    {
        id: "CT-001",
        name: "Japanese",
        code: "JP-CUISINE",
        description: "Traditional Japanese dishes with sushi, ramen, and tempura.",
        region: "East Asia",
        status: "active",
        recipe_count: 120,
        active_count: 95,
        last_active: "2024-07-10",
    },
    {
        id: "CT-002",
        name: "Italian",
        code: "IT-CUISINE",
        description: "Famous for pasta, pizza, and rich sauces.",
        region: "Europe",
        status: "active",
        recipe_count: 180,
        active_count: 150,
        last_active: "2024-06-30",
    },
    {
        id: "CT-003",
        name: "Mexican",
        code: "MX-CUISINE",
        description: "Spicy dishes featuring tacos, enchiladas, and tamales.",
        region: "Latin America",
        status: "active",
        recipe_count: 95,
        active_count: 80,
        last_active: "2024-07-15",
    },
    {
        id: "CT-004",
        name: "Thai",
        code: "TH-CUISINE",
        description: "Balance of sweet, sour, spicy, and savory flavors with curries and stir-fries.",
        region: "Southeast Asia",
        status: "active",
        recipe_count: 130,
        active_count: 110,
        last_active: "2024-07-12",
    },
    {
        id: "CT-005",
        name: "Indian",
        code: "IN-CUISINE",
        description: "Richly spiced curries, biryanis, and naan bread.",
        region: "South Asia",
        status: "inactive",
        recipe_count: 200,
        active_count: 175,
        last_active: "2024-05-22",
    },
    {
        id: "CT-006",
        name: "French",
        code: "FR-CUISINE",
        description: "Elegant dishes including croissants, coq au vin, and soufflés.",
        region: "Europe",
        status: "active",
        recipe_count: 160,
        active_count: 140,
        last_active: "2024-06-20",
    },
    {
        id: "CT-007",
        name: "Korean",
        code: "KR-CUISINE",
        description: "Kimchi, bibimbap, and Korean BBQ with bold flavors.",
        region: "East Asia",
        status: "active",
        recipe_count: 110,
        active_count: 90,
        last_active: "2024-07-08",
    },
    {
        id: "CT-008",
        name: "Mediterranean",
        code: "MED-CUISINE",
        description: "Healthy diet based on olive oil, fresh vegetables, and seafood.",
        region: "Mediterranean",
        status: "inactive",
        recipe_count: 140,
        active_count: 115,
        last_active: "2024-06-10",
    },
    {
        id: "CT-009",
        name: "American",
        code: "US-CUISINE",
        description: "Burgers, BBQ, and fast food staples.",
        region: "North America",
        status: "active",
        recipe_count: 90,
        active_count: 75,
        last_active: "2024-07-05",
    },
    {
        id: "CT-010",
        name: "Middle Eastern",
        code: "ME-CUISINE",
        description: "Dishes rich in spices, including hummus, kebabs, and falafel.",
        region: "Middle East",
        status: "active",
        recipe_count: 125,
        active_count: 100,
        last_active: "2024-07-14",
    },
];