import { PriceListDto } from "@/dtos/vendor-management";

export const mockPriceLists: PriceListDto[] = [
    {
        id: "pl-01",
        name: "Summer Sale",
        code: "SUMMER2025",
        description: "Discount for summer season",
        start_date: "2025-06-01",
        end_date: "2025-08-31",
        is_active: true,
    },
    {
        id: "pl-02",
        name: "Winter Sale",
        code: "WS001",
        description: "Year-end winter promotion",
        start_date: "2025-12-01",
        end_date: "2026-02-28",
        is_active: false,
    },
    {
        id: "pl-03",
        name: "Black Friday",
        code: "BF001",
        description: "One-day mega sale",
        start_date: "2025-11-28",
        end_date: "2025-11-28",
        is_active: true,
    },
    {
        id: "pl-04",
        name: "New Year Offer",
        code: "NY2026",
        description: "Special prices for the new year",
        start_date: "2025-12-31",
        end_date: "2026-01-02",
        is_active: false,
    },
    {
        id: "pl-05",
        name: "Back to School",
        code: "SCHOOL25",
        description: "Deals for students and teachers",
        start_date: "2025-07-15",
        end_date: "2025-09-01",
        is_active: true,
    },
    {
        id: "pl-06",
        name: "Flash Sale",
        code: "FLASH25",
        description: "24-hour flash discount",
        start_date: "2025-10-10",
        end_date: "2025-10-10",
        is_active: false,
    },
    {
        id: "pl-07",
        name: "Anniversary Promo",
        code: "ANNIV25",
        description: "Celebrating our 10th anniversary",
        start_date: "2025-05-01",
        end_date: "2025-05-10",
        is_active: true,
    },
    {
        id: "pl-08",
        name: "Clearance Sale",
        code: "CLEAR25",
        description: "End of stock clearance",
        start_date: "2025-09-01",
        end_date: "2025-09-30",
        is_active: true,
    },
    {
        id: "pl-09",
        name: "Loyalty Reward",
        code: "LOYAL25",
        description: "Special pricing for loyalty members",
        start_date: "2025-06-15",
        end_date: "2025-07-15",
        is_active: false,
    },
    {
        id: "pl-10",
        name: "Test Campaign",
        code: "TEST25",
        description: "Internal testing campaign",
        start_date: "2025-01-01",
        end_date: "2025-01-31",
        is_active: false,
    },
];
