import { NotificationDto } from "@/dtos/notification.dto";
import { FlaggedDto, PendingApprovalDto, PurchaseOrderlDto, PurchaseRequestDto, RecentApprovalDto } from "@/dtos/procurement.dto";

export const mockPendingApprovals: PendingApprovalDto[] = [
    {
        id: "pda-1",
        title: "Purchase Laptop",
        no_unit: 2,
        price: 50000,
        requestor: "John Doe",
        department: "IT",
        status: "Low",
    },
    {
        id: "pda-2",
        title: "Office Chairs",
        no_unit: 5,
        price: 15000,
        requestor: "Jane Smith",
        department: "HR",
        status: "Medium",
    },
    {
        id: "pda-3",
        title: "Projector",
        no_unit: 1,
        price: 25000,
        requestor: "Michael Brown",
        department: "Sales",
        status: "High",
    },
    {
        id: "pda-4",
        title: "Whiteboards",
        no_unit: 3,
        price: 9000,
        requestor: "Emily Johnson",
        department: "Operations",
        status: "Low",
    },
    {
        id: "pda-5",
        title: "Printer",
        no_unit: 2,
        price: 12000,
        requestor: "David Wilson",
        department: "Finance",
        status: "Medium",
    },
    {
        id: "pda-6",
        title: "Office Desks",
        no_unit: 4,
        price: 20000,
        requestor: "Emma Davis",
        department: "Admin",
        status: "High",
    },
    {
        id: "pda-7",
        title: "Air Conditioners",
        no_unit: 2,
        price: 35000,
        requestor: "Sophia Martinez",
        department: "Facilities",
        status: "Low",
    },
    {
        id: "pda-8",
        title: "Conference Table",
        no_unit: 1,
        price: 18000,
        requestor: "Olivia Taylor",
        department: "Management",
        status: "Medium",
    },
    {
        id: "pda-9",
        title: "Coffee Machine",
        no_unit: 1,
        price: 8000,
        requestor: "William Anderson",
        department: "HR",
        status: "High",
    },
    {
        id: "pda-10",
        title: "Software Licenses",
        no_unit: 10,
        price: 50000,
        requestor: "Daniel Thomas",
        department: "IT",
        status: "Low",
    },
];

export const mockFlaggedApprovals: FlaggedDto[] = [
    {
        id: "101",
        title: "High-End Monitors",
        no_unit: 3,
        price: 75000,
        requestor: "Alice Green",
        department: "IT",
        status: "Pending",
        flagged_reason: "Exceeds budget limit",
    },
    {
        id: "102",
        title: "Luxury Office Chairs",
        no_unit: 6,
        price: 45000,
        requestor: "Robert White",
        department: "HR",
        status: "Rejected",
        flagged_reason: "Unnecessary purchase",
    },
    {
        id: "103",
        title: "Custom Software Subscription",
        no_unit: 1,
        price: 90000,
        requestor: "Lucas Brown",
        department: "Development",
        status: "Pending",
        flagged_reason: "Requires additional approval",
    },
    {
        id: "104",
        title: "Security Camera System",
        no_unit: 4,
        price: 50000,
        requestor: "Sophia Wilson",
        department: "Facilities",
        status: "Approved",
        flagged_reason: "Requires IT security review",
    },
    {
        id: "105",
        title: "Office Renovation",
        no_unit: 1,
        price: 200000,
        requestor: "Ethan Martinez",
        department: "Management",
        status: "Pending",
        flagged_reason: "Exceeds company policy limit",
    },
    {
        id: "106",
        title: "High-Speed Internet Upgrade",
        no_unit: 1,
        price: 60000,
        requestor: "Charlotte Johnson",
        department: "IT",
        status: "Pending",
        flagged_reason: "Needs vendor evaluation",
    },
    {
        id: "107",
        title: "Luxury Coffee Machines",
        no_unit: 2,
        price: 25000,
        requestor: "Mason Taylor",
        department: "HR",
        status: "Rejected",
        flagged_reason: "Not essential for operations",
    },
    {
        id: "108",
        title: "Corporate Team Building Retreat",
        no_unit: 1,
        price: 120000,
        requestor: "Amelia Thomas",
        department: "Operations",
        status: "Pending",
        flagged_reason: "Requires CFO approval",
    },
    {
        id: "109",
        title: "Ergonomic Keyboards",
        no_unit: 10,
        price: 15000,
        requestor: "Liam Walker",
        department: "Development",
        status: "Approved",
        flagged_reason: "High return rate on previous orders",
    },
    {
        id: "110",
        title: "Electric Standing Desks",
        no_unit: 5,
        price: 90000,
        requestor: "Emma Harris",
        department: "Admin",
        status: "Pending",
        flagged_reason: "Needs space reallocation review",
    },
];

export const mockRecentApprovals: RecentApprovalDto[] = [
    {
        id: "rp-201",
        title: "Graphic Design Software",
        no_unit: 5,
        price: 75000,
        requestor: "Emily Carter",
        department: "Marketing",
        status: "Approved",
        date_approved: "2025-03-25",
    },
    {
        id: "rp-202",
        title: "Wireless Headsets",
        no_unit: 10,
        price: 30000,
        requestor: "James Anderson",
        department: "Customer Support",
        status: "Approved",
        date_approved: "2025-03-26",
    },
    {
        id: "rp-203",
        title: "Cloud Storage Subscription",
        no_unit: 1,
        price: 50000,
        requestor: "Sophia Bennett",
        department: "IT",
        status: "Approved",
        date_approved: "2025-03-27",
    },
];


export const mockNotiApproval: NotificationDto[] = [
    {
        id: "n-301",
        title: "New Purchase Request",
        message: "Your purchase request for office chairs has been submitted.",
        user_posted: "Prayuth Chan-o-cha",
        created_at: "2025-03-27T08:30:00Z",
        read: false,
    },
    {
        id: "n-302",
        title: "Approval Granted",
        message: "Your request for wireless headsets has been approved.",
        user_posted: "Prawit Wongsuwon",
        created_at: "2025-03-26T15:45:00Z",
        read: true,
    },
    {
        id: "n-303",
        title: "New Comment on Request",
        message: "The finance department has left a comment on your request.",
        user_posted: "Anutin Charnvirakul",
        created_at: "2025-03-26T10:15:00Z",
        read: false,
    },
    {
        id: "n-304",
        title: "System Maintenance",
        message: "Scheduled maintenance will occur on March 30, 2025.",
        user_posted: "Taksin Shinawatra",
        created_at: "2025-03-25T12:00:00Z",
        read: true,
    }
];

export const mockPurchaseRequests: PurchaseRequestDto[] = [
    {
        id: "PR-001",
        title: "Purchase of Office Chairs",
        status: "Pending",
        date_created: "2024-03-25",
        type: "Office Supplies",
        description: "Request to purchase 10 ergonomic office chairs for the HR department.",
        requestor: "John Doe",
        department: "Human Resources",
        amount: 1500,
        workflow_status: "Approval Pending",
    },
    {
        id: "PR-002",
        title: "Software License Renewal",
        status: "Approved",
        date_created: "2024-03-20",
        type: "IT Equipment",
        description: "Annual renewal of Adobe Creative Cloud licenses for the design team.",
        requestor: "Jane Smith",
        department: "IT",
        amount: 2500,
        workflow_status: "Completed",
    },
    {
        id: "PR-003",
        title: "New Laptops for Development Team",
        status: "Rejected",
        date_created: "2024-03-18",
        type: "Hardware",
        description: "Request to purchase 5 new MacBook Pro laptops for the development team.",
        requestor: "Michael Johnson",
        department: "Engineering",
        amount: 12000,
        workflow_status: "Rejected",
    },
    {
        id: "PR-004",
        title: "Marketing Campaign Budget",
        status: "Pending",
        date_created: "2024-03-27",
        type: "Marketing",
        description: "Request for budget allocation for Q2 social media ads campaign.",
        requestor: "Emily Davis",
        department: "Marketing",
        amount: 5000,
        workflow_status: "Under Review",
    },
    {
        id: "PR-005",
        title: "Office Stationery Refill",
        status: "Approved",
        date_created: "2024-03-22",
        type: "Office Supplies",
        description: "Restocking essential office stationery such as pens, papers, and binders.",
        requestor: "Robert Wilson",
        department: "Administration",
        amount: 700,
        workflow_status: "Completed",
    }
];


export const mockPurchaseOrders: PurchaseOrderlDto[] = [
    {
        id: "PO-001",
        department: "Human Resources",
        status: "Pending",
        date_created: "2024-03-25",
        delivery_date: "2024-04-01",
        po_number: "HR-20240325-001",
        currency: "USD",
        net_amount: 1500,
        tax_amount: 75,
        amount: 1575,
    },
    {
        id: "PO-002",
        department: "IT",
        status: "Approved",
        date_created: "2024-03-20",
        delivery_date: "2024-03-30",
        po_number: "IT-20240320-002",
        currency: "USD",
        net_amount: 2500,
        tax_amount: 125,
        amount: 2625,
    },
    {
        id: "PO-003",
        department: "Engineering",
        status: "Rejected",
        date_created: "2024-03-18",
        delivery_date: "2024-03-28",
        po_number: "ENG-20240318-003",
        currency: "EUR",
        net_amount: 12000,
        tax_amount: 600,
        amount: 12600,
    },
    {
        id: "PO-004",
        department: "Marketing",
        status: "Pending",
        date_created: "2024-03-27",
        delivery_date: "2024-04-05",
        po_number: "MKT-20240327-004",
        currency: "USD",
        net_amount: 5000,
        tax_amount: 250,
        amount: 5250,
    },
    {
        id: "PO-005",
        department: "Administration",
        status: "Approved",
        date_created: "2024-03-22",
        delivery_date: "2024-03-29",
        po_number: "ADM-20240322-005",
        currency: "USD",
        net_amount: 700,
        tax_amount: 35,
        amount: 735,
    }
];
