import { FlaggedDto, PendingApprovalDto } from "@/dtos/procurement.dto";

export const mockPendingApprovals: PendingApprovalDto[] = [
    {
        id: "pda-1",
        title: "Purchase Laptop",
        no_unit: 2,
        price: 50000,
        requestor: "John Doe",
        department: "IT",
        status: "Low",
    },
    {
        id: "pda-2",
        title: "Office Chairs",
        no_unit: 5,
        price: 15000,
        requestor: "Jane Smith",
        department: "HR",
        status: "Medium",
    },
    {
        id: "pda-3",
        title: "Projector",
        no_unit: 1,
        price: 25000,
        requestor: "Michael Brown",
        department: "Sales",
        status: "High",
    },
    {
        id: "pda-4",
        title: "Whiteboards",
        no_unit: 3,
        price: 9000,
        requestor: "Emily Johnson",
        department: "Operations",
        status: "Low",
    },
    {
        id: "pda-5",
        title: "Printer",
        no_unit: 2,
        price: 12000,
        requestor: "David Wilson",
        department: "Finance",
        status: "Medium",
    },
    {
        id: "pda-6",
        title: "Office Desks",
        no_unit: 4,
        price: 20000,
        requestor: "Emma Davis",
        department: "Admin",
        status: "High",
    },
    {
        id: "pda-7",
        title: "Air Conditioners",
        no_unit: 2,
        price: 35000,
        requestor: "Sophia Martinez",
        department: "Facilities",
        status: "Low",
    },
    {
        id: "pda-8",
        title: "Conference Table",
        no_unit: 1,
        price: 18000,
        requestor: "Olivia Taylor",
        department: "Management",
        status: "Medium",
    },
    {
        id: "pda-9",
        title: "Coffee Machine",
        no_unit: 1,
        price: 8000,
        requestor: "William Anderson",
        department: "HR",
        status: "High",
    },
    {
        id: "pda-10",
        title: "Software Licenses",
        no_unit: 10,
        price: 50000,
        requestor: "Daniel Thomas",
        department: "IT",
        status: "Low",
    },
];

export const mockFlaggedApprovals: FlaggedDto[] = [
    {
        id: "101",
        title: "High-End Monitors",
        no_unit: 3,
        price: 75000,
        requestor: "Alice Green",
        department: "IT",
        status: "Pending",
        flagged_reason: "Exceeds budget limit",
    },
    {
        id: "102",
        title: "Luxury Office Chairs",
        no_unit: 6,
        price: 45000,
        requestor: "Robert White",
        department: "HR",
        status: "Rejected",
        flagged_reason: "Unnecessary purchase",
    },
    {
        id: "103",
        title: "Custom Software Subscription",
        no_unit: 1,
        price: 90000,
        requestor: "Lucas Brown",
        department: "Development",
        status: "Pending",
        flagged_reason: "Requires additional approval",
    },
    {
        id: "104",
        title: "Security Camera System",
        no_unit: 4,
        price: 50000,
        requestor: "Sophia Wilson",
        department: "Facilities",
        status: "Approved",
        flagged_reason: "Requires IT security review",
    },
    {
        id: "105",
        title: "Office Renovation",
        no_unit: 1,
        price: 200000,
        requestor: "Ethan Martinez",
        department: "Management",
        status: "Pending",
        flagged_reason: "Exceeds company policy limit",
    },
    {
        id: "106",
        title: "High-Speed Internet Upgrade",
        no_unit: 1,
        price: 60000,
        requestor: "Charlotte Johnson",
        department: "IT",
        status: "Pending",
        flagged_reason: "Needs vendor evaluation",
    },
    {
        id: "107",
        title: "Luxury Coffee Machines",
        no_unit: 2,
        price: 25000,
        requestor: "Mason Taylor",
        department: "HR",
        status: "Rejected",
        flagged_reason: "Not essential for operations",
    },
    {
        id: "108",
        title: "Corporate Team Building Retreat",
        no_unit: 1,
        price: 120000,
        requestor: "Amelia Thomas",
        department: "Operations",
        status: "Pending",
        flagged_reason: "Requires CFO approval",
    },
    {
        id: "109",
        title: "Ergonomic Keyboards",
        no_unit: 10,
        price: 15000,
        requestor: "Liam Walker",
        department: "Development",
        status: "Approved",
        flagged_reason: "High return rate on previous orders",
    },
    {
        id: "110",
        title: "Electric Standing Desks",
        no_unit: 5,
        price: 90000,
        requestor: "Emma Harris",
        department: "Admin",
        status: "Pending",
        flagged_reason: "Needs space reallocation review",
    },
];
