import { NotificationDto } from "@/dtos/notification.dto";
import { ActivityPrDto, AttachmentPrDto, BudgetPrDto, CreditNoteDto, FlaggedDto, GoodsReceivedNoteDto, ItemDetailPrDto, PendingApprovalDto, PurchaseOrderlDto, PurchaseRequestDto, PurchaseRequestTemplateDto, RecentApprovalDto, VendorComparisonDto, WorkflowPrDto } from "@/dtos/procurement.dto";

export const mockPendingApprovals: PendingApprovalDto[] = [
    {
        id: "pda-1",
        title: "Purchase Laptop",
        no_unit: 2,
        price: 50000,
        requestor: "John Doe",
        department: "IT",
        status: "Low",
    },
    {
        id: "pda-2",
        title: "Office Chairs",
        no_unit: 5,
        price: 15000,
        requestor: "Jane Smith",
        department: "HR",
        status: "Medium",
    },
    {
        id: "pda-3",
        title: "Projector",
        no_unit: 1,
        price: 25000,
        requestor: "Michael Brown",
        department: "Sales",
        status: "High",
    },
    {
        id: "pda-4",
        title: "Whiteboards",
        no_unit: 3,
        price: 9000,
        requestor: "Emily Johnson",
        department: "Operations",
        status: "Low",
    },
    {
        id: "pda-5",
        title: "Printer",
        no_unit: 2,
        price: 12000,
        requestor: "David Wilson",
        department: "Finance",
        status: "Medium",
    },
    {
        id: "pda-6",
        title: "Office Desks",
        no_unit: 4,
        price: 20000,
        requestor: "Emma Davis",
        department: "Admin",
        status: "High",
    },
    {
        id: "pda-7",
        title: "Air Conditioners",
        no_unit: 2,
        price: 35000,
        requestor: "Sophia Martinez",
        department: "Facilities",
        status: "Low",
    },
    {
        id: "pda-8",
        title: "Conference Table",
        no_unit: 1,
        price: 18000,
        requestor: "Olivia Taylor",
        department: "Management",
        status: "Medium",
    },
    {
        id: "pda-9",
        title: "Coffee Machine",
        no_unit: 1,
        price: 8000,
        requestor: "William Anderson",
        department: "HR",
        status: "High",
    },
    {
        id: "pda-10",
        title: "Software Licenses",
        no_unit: 10,
        price: 50000,
        requestor: "Daniel Thomas",
        department: "IT",
        status: "Low",
    },
];

export const mockFlaggedApprovals: FlaggedDto[] = [
    {
        id: "101",
        title: "High-End Monitors",
        no_unit: 3,
        price: 75000,
        requestor: "Alice Green",
        department: "IT",
        status: "Low",
        flagged_reason: "Exceeds budget limit",
    },
    {
        id: "102",
        title: "Luxury Office Chairs",
        no_unit: 6,
        price: 45000,
        requestor: "Robert White",
        department: "HR",
        status: "Medium",
        flagged_reason: "Unnecessary purchase",
    },
    {
        id: "103",
        title: "Custom Software Subscription",
        no_unit: 1,
        price: 90000,
        requestor: "Lucas Brown",
        department: "Development",
        status: "High",
        flagged_reason: "Requires additional approval",
    },
    {
        id: "104",
        title: "Security Camera System",
        no_unit: 4,
        price: 50000,
        requestor: "Sophia Wilson",
        department: "Facilities",
        status: "Medium",
        flagged_reason: "Requires IT security review",
    },
    {
        id: "105",
        title: "Office Renovation",
        no_unit: 1,
        price: 200000,
        requestor: "Ethan Martinez",
        department: "Management",
        status: "Medium",
        flagged_reason: "Exceeds company policy limit",
    },
    {
        id: "106",
        title: "High-Speed Internet Upgrade",
        no_unit: 1,
        price: 60000,
        requestor: "Charlotte Johnson",
        department: "IT",
        status: "Medium",
        flagged_reason: "Needs vendor evaluation",
    },
    {
        id: "107",
        title: "Luxury Coffee Machines",
        no_unit: 2,
        price: 25000,
        requestor: "Mason Taylor",
        department: "HR",
        status: "Medium",
        flagged_reason: "Not essential for operations",
    },
    {
        id: "108",
        title: "Corporate Team Building Retreat",
        no_unit: 1,
        price: 120000,
        requestor: "Amelia Thomas",
        department: "Operations",
        status: "Medium",
        flagged_reason: "Requires CFO approval",
    },
    {
        id: "109",
        title: "Ergonomic Keyboards",
        no_unit: 10,
        price: 15000,
        requestor: "Liam Walker",
        department: "Development",
        status: "Medium",
        flagged_reason: "High return rate on previous orders",
    },
    {
        id: "110",
        title: "Electric Standing Desks",
        no_unit: 5,
        price: 90000,
        requestor: "Emma Harris",
        department: "Admin",
        status: "High",
        flagged_reason: "Needs space reallocation review",
    },
];

export const mockRecentApprovals: RecentApprovalDto[] = [
    {
        id: "rp-201",
        title: "Graphic Design Software",
        no_unit: 5,
        price: 75000,
        requestor: "Emily Carter",
        department: "Marketing",
        status: "Approved",
        date_approved: "2025-03-25",
    },
    {
        id: "rp-202",
        title: "Wireless Headsets",
        no_unit: 10,
        price: 30000,
        requestor: "James Anderson",
        department: "Customer Support",
        status: "Approved",
        date_approved: "2025-03-26",
    },
    {
        id: "rp-203",
        title: "Cloud Storage Subscription",
        no_unit: 1,
        price: 50000,
        requestor: "Sophia Bennett",
        department: "IT",
        status: "Pending",
        date_approved: "2025-03-27",
    },
    {
        id: "rp-204",
        title: "Office Chairs",
        no_unit: 10,
        price: 15000,
        requestor: "John Doe",
        department: "HR",
        status: "Rejected",
        date_approved: "2025-03-28",
    },
];


export const mockNotiApproval: NotificationDto[] = [
    {
        id: "n-301",
        title: "New Purchase Request",
        message: "Your purchase request for office chairs has been submitted.",
        user_posted: "Thitiphong Srisavat",
        created_at: "2025-03-27T08:30:00Z",
        read: false,
    },
    {
        id: "n-302",
        title: "Approval Granted",
        message: "Your request for wireless headsets has been approved.",
        user_posted: "Chaiwat Chaiyakul",
        created_at: "2025-03-26T15:45:00Z",
        read: true,
    },
    {
        id: "n-303",
        title: "New Comment on Request",
        message: "The finance department has left a comment on your request.",
        user_posted: "Narongdech Ngamkham",
        created_at: "2025-03-26T10:15:00Z",
        read: false,
    },
    {
        id: "n-304",
        title: "System Maintenance",
        message: "Scheduled maintenance will occur on March 30, 2025.",
        user_posted: "Oralik Musikkawong",
        created_at: "2025-03-25T12:00:00Z",
        read: true,
    }
];

export const mockPurchaseRequests: PurchaseRequestDto[] = [
    {
        id: "PR-001",
        pr_no: "pr-no-001",
        title: "Purchase of Office Chairs",
        status: "Draft",
        date_created: "2024-03-25",
        type: "Office Supplies",
        description: "Request to purchase 10 ergonomic office chairs for the HR department.",
        requestor: "John Doe",
        department: "Human Resources",
        amount: 1500.00,
        workflow_status: "Approval Pending",
        delivery_date: "2024-04-01",
    },
    {
        id: "PR-002",
        pr_no: "pr-no-002",
        title: "Software License Renewal",
        status: "Submitted",
        date_created: "2024-03-20",
        type: "IT Equipment",
        description: "Annual renewal of Adobe Creative Cloud licenses for the design team.",
        requestor: "Jane Smith",
        department: "IT",
        amount: 2500.00,
        workflow_status: "Completed",
        delivery_date: "2024-05-01",
    },
    {
        id: "PR-003",
        pr_no: "pr-no-003",
        title: "New Laptops for Development Team",
        status: "Completed",
        date_created: "2024-03-18",
        type: "Hardware",
        description: "Request to purchase 5 new MacBook Pro laptops for the development team.",
        requestor: "Michael Johnson",
        department: "Engineering",
        amount: 12000.00,
        workflow_status: "Rejected",
        delivery_date: "2024-08-01",
    },
    {
        id: "PR-004",
        pr_no: "pr-no-004",
        title: "Marketing Campaign Budget",
        status: "Draft",
        date_created: "2024-03-27",
        type: "Marketing",
        description: "Request for budget allocation for Q2 social media ads campaign.",
        requestor: "Emily Davis",
        department: "Marketing",
        amount: 5000.00,
        workflow_status: "Under Review",
        delivery_date: "2024-09-01",
    },
    {
        id: "PR-005",
        pr_no: "pr-no-005",
        title: "Office Stationery Refill",
        status: "Draft",
        date_created: "2024-03-22",
        type: "Office Supplies",
        description: "Restocking essential office stationery such as pens, papers, and binders.",
        requestor: "Robert Wilson",
        department: "Administration",
        amount: 700.00,
        workflow_status: "Completed",
        delivery_date: "2024-09-08",
    },
    {
        id: "PR-006",
        pr_no: "pr-no-006",
        title: "Office Chairs",
        status: "Completed",
        date_created: "2024-03-25",
        type: "Office Supplies",
        description: "Request to purchase 10 ergonomic office chairs for the HR department.",
        requestor: "John Doe",
        department: "Human Resources",
        amount: 1500.00,
        workflow_status: "Approval Pending",
        delivery_date: "2024-09-08",
    }
];

export const mockPurchaseOrders: PurchaseOrderlDto[] = [
    {
        id: "PO-001",
        vendor: "Apple",
        status: "Sent",
        date_created: "2024-03-25",
        delivery_date: "2024-04-01",
        po_number: "HR-20240325-001",
        currency: "USD",
        net_amount: 1500.00,
        tax_amount: 75.00,
        amount: 1575.00,
    },
    {
        id: "PO-002",
        vendor: "Samsung",
        status: "Approved",
        date_created: "2024-03-20",
        delivery_date: "2024-03-30",
        po_number: "IT-20240320-002",
        currency: "USD",
        net_amount: 2500,
        tax_amount: 125,
        amount: 2625,
    },
    {
        id: "PO-003",
        vendor: "LG",
        status: "Rejected",
        date_created: "2024-03-18",
        delivery_date: "2024-03-28",
        po_number: "ENG-20240318-003",
        currency: "EUR",
        net_amount: 12000,
        tax_amount: 600,
        amount: 12600,
    },
    {
        id: "PO-004",
        vendor: "Sony",
        status: "Pending",
        date_created: "2024-03-27",
        delivery_date: "2024-04-05",
        po_number: "MKT-20240327-004",
        currency: "USD",
        net_amount: 5000,
        tax_amount: 250,
        amount: 5250,
    },
    {
        id: "PO-005",
        vendor: "Dell",
        status: "Approved",
        date_created: "2024-03-22",
        delivery_date: "2024-03-29",
        po_number: "ADM-20240322-005",
        currency: "USD",
        net_amount: 700,
        tax_amount: 35,
        amount: 735,
    }
];

export const mockGoodsReceivedNotes: GoodsReceivedNoteDto[] = [
    {
        id: "GRN-001",
        department: "Human Resources",
        status: "Approved",
        date_created: "2024-03-10",
        invoice_date: "2024-03-12",
        grn_number: "HR-20240310-001",
        currency: "USD",
        net_amount: 1500,
        tax_amount: 75,
        amount: 1575,
    },
    {
        id: "GRN-002",
        department: "IT",
        status: "Pending",
        date_created: "2024-03-15",
        invoice_date: "2024-03-18",
        grn_number: "IT-20240315-002",
        currency: "USD",
        net_amount: 3200,
        tax_amount: 160,
        amount: 3360,
    },
    {
        id: "GRN-003",
        department: "Engineering",
        status: "Approved",
        date_created: "2024-03-08",
        invoice_date: "2024-03-10",
        grn_number: "ENG-20240308-003",
        currency: "EUR",
        net_amount: 8200,
        tax_amount: 410,
        amount: 8610,
    },
    {
        id: "GRN-004",
        department: "Marketing",
        status: "Pending",
        date_created: "2024-03-20",
        invoice_date: "2024-03-22",
        grn_number: "MKT-20240320-004",
        currency: "USD",
        net_amount: 2900,
        tax_amount: 145,
        amount: 3045,
    },
    {
        id: "GRN-005",
        department: "Administration",
        status: "Rejected",
        date_created: "2024-03-05",
        invoice_date: "2024-03-07",
        grn_number: "ADM-20240305-005",
        currency: "USD",
        net_amount: 680,
        tax_amount: 34,
        amount: 714,
    },
    {
        id: "GRN-006",
        department: "Finance",
        status: "Pending",
        date_created: "2024-03-17",
        invoice_date: "2024-03-19",
        grn_number: "FIN-20240317-006",
        currency: "USD",
        net_amount: 5400,
        tax_amount: 270,
        amount: 5670,
    },
    {
        id: "GRN-007",
        department: "Logistics",
        status: "Rejected",
        date_created: "2024-03-12",
        invoice_date: "2024-03-14",
        grn_number: "LOG-20240312-007",
        currency: "USD",
        net_amount: 4500,
        tax_amount: 225,
        amount: 4725,
    },
    {
        id: "GRN-008",
        department: "Procurement",
        status: "Pending",
        date_created: "2024-03-14",
        invoice_date: "2024-03-16",
        grn_number: "PRC-20240314-008",
        currency: "USD",
        net_amount: 3750,
        tax_amount: 188,
        amount: 3938,
    },
    {
        id: "GRN-009",
        department: "Customer Service",
        status: "Approved",
        date_created: "2024-03-09",
        invoice_date: "2024-03-11",
        grn_number: "CS-20240309-009",
        currency: "USD",
        net_amount: 2100,
        tax_amount: 105,
        amount: 2205,
    },
    {
        id: "GRN-010",
        department: "Sales",
        status: "Rejected",
        date_created: "2024-03-22",
        invoice_date: "2024-03-24",
        grn_number: "SLS-20240322-010",
        currency: "USD",
        net_amount: 6000,
        tax_amount: 300,
        amount: 6300,
    }
];

export const mockCreditNotes: CreditNoteDto[] = [
    {
        id: "CDN-001",
        cdn_number: "CDN-20240301-001",
        title: "Credit Note for Invoice INV-1001",
        date_created: "2024-03-01",
        vendor: "ABC Supplies Ltd.",
        doc_no: "INV-1001",
        doc_date: "2024-02-25",
        net_amount: 1200,
        tax_amount: 60,
        amount: 1260,
        status: "Approved",
    },
    {
        id: "CDN-002",
        cdn_number: "CDN-20240302-002",
        title: "Refund for Overpayment",
        date_created: "2024-03-02",
        vendor: "XYZ Traders",
        doc_no: "INV-1002",
        doc_date: "2024-02-26",
        net_amount: 800,
        tax_amount: 40,
        amount: 840,
        status: "Pending",
    },
    {
        id: "CDN-003",
        cdn_number: "CDN-20240303-003",
        title: "Price Adjustment for Product A",
        date_created: "2024-03-03",
        vendor: "LMN Enterprises",
        doc_no: "INV-1003",
        doc_date: "2024-02-27",
        net_amount: 1500,
        tax_amount: 75,
        amount: 1575,
        status: "Draft",
    },
    {
        id: "CDN-004",
        cdn_number: "CDN-20240304-004",
        title: "Discount for Bulk Order",
        date_created: "2024-03-04",
        vendor: "Global Parts Inc.",
        doc_no: "INV-1004",
        doc_date: "2024-02-28",
        net_amount: 2300,
        tax_amount: 115,
        amount: 2415,
        status: "Draft",
    },
    {
        id: "CDN-005",
        cdn_number: "CDN-20240305-005",
        title: "Defective Item Compensation",
        date_created: "2024-03-05",
        vendor: "Tech Solutions",
        doc_no: "INV-1005",
        doc_date: "2024-03-01",
        net_amount: 1750,
        tax_amount: 87.5,
        amount: 1837.5,
        status: "Rejected",
    },
    {
        id: "CDN-006",
        cdn_number: "CDN-20240306-006",
        title: "Return of Unused Items",
        date_created: "2024-03-06",
        vendor: "ABC Supplies Ltd.",
        doc_no: "INV-1006",
        doc_date: "2024-03-02",
        net_amount: 950,
        tax_amount: 47.5,
        amount: 997.5,
        status: "Pending",
    },
    {
        id: "CDN-007",
        cdn_number: "CDN-20240307-007",
        title: "Loyalty Discount",
        date_created: "2024-03-07",
        vendor: "XYZ Traders",
        doc_no: "INV-1007",
        doc_date: "2024-03-03",
        net_amount: 1100,
        tax_amount: 55,
        amount: 1155,
        status: "Approved",
    },
    {
        id: "CDN-008",
        cdn_number: "CDN-20240308-008",
        title: "Special Promotion Credit",
        date_created: "2024-03-08",
        vendor: "LMN Enterprises",
        doc_no: "INV-1008",
        doc_date: "2024-03-04",
        net_amount: 2100,
        tax_amount: 105,
        amount: 2205,
        status: "Rejected",
    },
    {
        id: "CDN-009",
        cdn_number: "CDN-20240309-009",
        title: "Incorrect Billing Adjustment",
        date_created: "2024-03-09",
        vendor: "Global Parts Inc.",
        doc_no: "INV-1009",
        doc_date: "2024-03-05",
        net_amount: 1250,
        tax_amount: 62.5,
        amount: 1312.5,
        status: "Rejected",
    },
    {
        id: "CDN-010",
        cdn_number: "CDN-20240310-010",
        title: "Service Charge Reimbursement",
        date_created: "2024-03-10",
        vendor: "Tech Solutions",
        doc_no: "INV-1010",
        doc_date: "2024-03-06",
        net_amount: 3000,
        tax_amount: 150,
        amount: 3150,
        status: "Pending",
    },
];


export const mockPurchaseRequestTemplates: PurchaseRequestTemplateDto[] = [
    {
        id: "PRT-001",
        title: "Office Supplies Purchase",
        department: "Administration",
        status: "Pending",
        date_created: "2024-03-01",
        type: "Standard",
        prt_number: "PRT-20240301-001",
        requestor: "John Doe",
        amount: 1500,
        workflow_status: "Approval Pending",
    },
    {
        id: "PRT-002",
        title: "IT Equipment Upgrade",
        department: "IT",
        status: "Approved",
        date_created: "2024-03-02",
        type: "Urgent",
        prt_number: "PRT-20240302-002",
        requestor: "Alice Smith",
        amount: 7500,
        workflow_status: "Completed",
    },
    {
        id: "PRT-003",
        title: "Marketing Campaign Materials",
        department: "Marketing",
        status: "Pending",
        date_created: "2024-03-03",
        type: "Standard",
        prt_number: "PRT-20240303-003",
        requestor: "Bob Johnson",
        amount: 3200,
        workflow_status: "Under Review",
    },
    {
        id: "PRT-004",
        title: "New Employee Workstations",
        department: "HR",
        status: "Rejected",
        date_created: "2024-03-04",
        type: "Capital Expense",
        prt_number: "PRT-20240304-004",
        requestor: "Emily White",
        amount: 12000,
        workflow_status: "Rejected",
    },
    {
        id: "PRT-005",
        title: "Conference Room Renovation",
        department: "Facilities",
        status: "Approved",
        date_created: "2024-03-05",
        type: "Project",
        prt_number: "PRT-20240305-005",
        requestor: "Michael Brown",
        amount: 20000,
        workflow_status: "Completed",
    },
    {
        id: "PRT-006",
        title: "Annual Office Supplies Restock",
        department: "Administration",
        status: "Pending",
        date_created: "2024-03-06",
        type: "Bulk Purchase",
        prt_number: "PRT-20240306-006",
        requestor: "Sarah Wilson",
        amount: 5000,
        workflow_status: "Approval Pending",
    },
    {
        id: "PRT-007",
        title: "Software License Renewal",
        department: "IT",
        status: "Approved",
        date_created: "2024-03-07",
        type: "Service",
        prt_number: "PRT-20240307-007",
        requestor: "David Miller",
        amount: 15000,
        workflow_status: "Completed",
    },
    {
        id: "PRT-008",
        title: "Trade Show Booth Setup",
        department: "Marketing",
        status: "Pending",
        date_created: "2024-03-08",
        type: "Event",
        prt_number: "PRT-20240308-008",
        requestor: "Laura Taylor",
        amount: 8500,
        workflow_status: "Under Review",
    },
    {
        id: "PRT-009",
        title: "Security System Upgrade",
        department: "Facilities",
        status: "Rejected",
        date_created: "2024-03-09",
        type: "Infrastructure",
        prt_number: "PRT-20240309-009",
        requestor: "James Anderson",
        amount: 18000,
        workflow_status: "Rejected",
    },
    {
        id: "PRT-010",
        title: "Employee Training Program",
        department: "HR",
        status: "Approved",
        date_created: "2024-03-10",
        type: "Education",
        prt_number: "PRT-20240310-010",
        requestor: "Sophia Martinez",
        amount: 6000,
        workflow_status: "Completed",
    },
];

export const mockItemDetailPrData: ItemDetailPrDto[] = [
    {
        id: "PR-001",
        location: "New York Warehouse",
        product_name: "Laptop Dell XPS 15",
        description: "High-performance laptop with Intel i7 processor",
        order_unit: "pcs",
        inv_unit: "pcs",
        request_qty: 10,
        on_order_qty: 5,
        approved_qty: 8,
        on_hand_qty: 12,
        base_currency: "USD",
        price: 1500,
        total_price: 12000,
        status: "Approved",
    },
    {
        id: "PR-002",
        location: "Los Angeles Office",
        product_name: "Wireless Keyboard",
        description: "Ergonomic keyboard with Bluetooth connectivity",
        order_unit: "pcs",
        inv_unit: "pcs",
        request_qty: 20,
        on_order_qty: 10,
        approved_qty: 15,
        on_hand_qty: 25,
        base_currency: "USD",
        price: 50,
        total_price: 750,
        status: "Pending",
    },
    {
        id: "PR-003",
        location: "Chicago HQ",
        product_name: "Office Chair",
        description: "Adjustable height with lumbar support",
        order_unit: "pcs",
        inv_unit: "pcs",
        request_qty: 5,
        on_order_qty: 2,
        approved_qty: 4,
        on_hand_qty: 6,
        base_currency: "USD",
        price: 200,
        total_price: 800,
        status: "Approved",
    },
    {
        id: "PR-004",
        location: "Houston Warehouse",
        product_name: "Printer Ink Cartridge",
        description: "Black ink cartridge for HP LaserJet",
        order_unit: "packs",
        inv_unit: "packs",
        request_qty: 30,
        on_order_qty: 10,
        approved_qty: 25,
        on_hand_qty: 50,
        base_currency: "USD",
        price: 30,
        total_price: 750,
        status: "Pending",
    },
    {
        id: "PR-005",
        location: "San Francisco Office",
        product_name: "External Hard Drive 1TB",
        description: "USB 3.0 external storage drive",
        order_unit: "pcs",
        inv_unit: "pcs",
        request_qty: 15,
        on_order_qty: 5,
        approved_qty: 12,
        on_hand_qty: 20,
        base_currency: "USD",
        price: 80,
        total_price: 960,
        status: "Approved",
    }
];

export const mockBudgetPrData: BudgetPrDto[] = [
    {
        id: "BUD-001",
        location: "New York Office",
        category: "IT Equipment",
        total_budget: 50000,
        dept_head_approval: 45000,
        po_approval: 42000,
        actual_gl: 40000,
        available_budget: 10000,
        current_budget: 5000,
    },
    {
        id: "BUD-002",
        location: "Los Angeles Warehouse",
        category: "Office Supplies",
        total_budget: 20000,
        dept_head_approval: 18000,
        po_approval: 16000,
        actual_gl: 15000,
        available_budget: 5000,
        current_budget: 3000,
    },
    {
        id: "BUD-003",
        location: "Chicago HQ",
        category: "Marketing",
        total_budget: 75000,
        dept_head_approval: 70000,
        po_approval: 65000,
        actual_gl: 60000,
        available_budget: 15000,
        current_budget: 7000,
    },
    {
        id: "BUD-004",
        location: "Houston Branch",
        category: "R&D",
        total_budget: 90000,
        dept_head_approval: 85000,
        po_approval: 82000,
        actual_gl: 80000,
        available_budget: 10000,
        current_budget: 4000,
    },
    {
        id: "BUD-005",
        location: "San Francisco Office",
        category: "Operations",
        total_budget: 60000,
        dept_head_approval: 55000,
        po_approval: 50000,
        actual_gl: 48000,
        available_budget: 12000,
        current_budget: 6000,
    },
];

export const mockWorkflowPrData: WorkflowPrDto[] = [
    {
        id: "WF-001",
        stage: "Initial Review",
        approver: "John Doe",
        status: "Approved",
        date_approved: "2024-03-10",
        comments: "Reviewed and approved without any issues.",
    },
    {
        id: "WF-002",
        stage: "Department Head Approval",
        approver: "Jane Smith",
        status: "Pending",
        date_approved: "",
        comments: "Waiting for department head approval.",
    },
    {
        id: "WF-003",
        stage: "Finance Review",
        approver: "Michael Johnson",
        status: "Rejected",
        date_approved: "2024-03-12",
        comments: "Budget exceeded the allocated amount.",
    },
    {
        id: "WF-004",
        stage: "Final Approval",
        approver: "Emily Davis",
        status: "Approved",
        date_approved: "2024-03-15",
        comments: "All conditions met, final approval granted.",
    },
    {
        id: "WF-005",
        stage: "Initial Review",
        approver: "William Brown",
        status: "Approved",
        date_approved: "2024-03-05",
        comments: "Checked all documents, everything is fine.",
    }
];


export const mockAttachments: AttachmentPrDto[] = [
    {
        id: "1",
        name: "Purchase_Request_Form.pdf",
        type: "PDF",
        size: "2.5 MB",
        uploadedBy: "John Doe",
        uploadedAt: "2024-03-20 14:30",
    },
    {
        id: "2",
        name: "Budget_Details.csv",
        type: "CSV",
        size: "1.2 MB",
        uploadedBy: "Jane Smith",
        uploadedAt: "2024-03-20 15:45",
    },
    {
        id: "3",
        name: "Quotation_Comparison.xlsx",
        type: "Excel",
        size: "3.8 MB",
        uploadedBy: "Mike Johnson",
        uploadedAt: "2024-03-20 16:15",
    },
];



export const mockActivities: ActivityPrDto[] = [
    {
        id: "1",
        timestamp: "2024-03-20 14:30",
        action: {
            label: "Created",
            variant: "default"
        },
        user: "John Doe",
        details: "Purchase request created"
    },
    {
        id: "2",
        timestamp: "2024-03-20 15:45",
        action: {
            label: "Submitted",
            variant: "success"
        },
        user: "John Doe",
        details: "Purchase request submitted for approval"
    },
    {
        id: "3",
        timestamp: "2024-03-20 16:15",
        action: {
            label: "Approved",
            variant: "success"
        },
        user: "Jane Smith",
        details: "Purchase request approved by Purchasing Department"
    },
    {
        id: "4",
        timestamp: "2024-03-20 17:30",
        action: {
            label: "Rejected",
            variant: "destructive"
        },
        user: "Mike Johnson",
        details: "Purchase request rejected by Finance Department - Budget exceeded"
    },
    {
        id: "5",
        timestamp: "2024-03-20 18:00",
        action: {
            label: "Modified",
            variant: "warning"
        },
        user: "John Doe",
        details: "Purchase request modified based on feedback"
    }
];

export const mockVendorComparisonData: VendorComparisonDto[] = [
    {
        id: 'vc-001',
        vendor_name: 'SCG Chemical',
        status: true,
        rating: 4.5,
        score: 87,
        res_time: 84,
        delivery_time: 10,
    },
    {
        id: 'vc-002',
        vendor_name: 'PTT Lubricants',
        status: false,
        rating: 3.8,
        score: 75,
        res_time: 150,
        delivery_time: 2,
    },
    {
        id: 'vc-003',
        vendor_name: 'HMC Polymer',
        status: true,
        rating: 4.9,
        score: 92,
        res_time: 100,
        delivery_time: 5,
    },
    {
        id: 'vc-004',
        vendor_name: 'Dow Chemical',
        status: true,
        rating: 4.5,
        score: 60,
        res_time: 100,
        delivery_time: 3,
    },
    {
        id: 'vc-005',
        vendor_name: 'PPG Industries',
        status: false,
        rating: 4.5,
        score: 87,
        res_time: 120,
        delivery_time: 2,
    },
    {
        id: 'vc-006',
        vendor_name: 'BASF',
        status: true,
        rating: 3.5,
        score: 99,
        res_time: 300,
        delivery_time: 9,
    },
    {
        id: 'vc-007',
        vendor_name: 'BSAA',
        status: true,
        rating: 2.5,
        score: 87,
        res_time: 64,
        delivery_time: 1,
    },
    {
        id: 'vc-008',
        vendor_name: 'SRF Industries',
        status: false,
        rating: 4.8,
        score: 95,
        res_time: 80,
        delivery_time: 7,
    },
    {
        id: 'vc-009',
        vendor_name: 'Huaweii',
        status: true,
        rating: 4.5,
        score: 33,
        res_time: 62,
        delivery_time: 6,
    },
    {
        id: 'vc-010',
        vendor_name: 'Samsung',
        status: true,
        rating: 4.5,
        score: 78,
        res_time: 77,
        delivery_time: 9,
    }
];
