import { ProductDetailDto, ProductDto } from "@/dtos/product.dto";

export const mockProducts: ProductDto[] = [
    {
        id: "pd-1",
        name: "Running Shoes",
        description: "Lightweight running shoes for daily training.",
        category: "Footwear",
        sub_category: "Shoes",
        item_group: "Sports",
        status: true,
    },
    {
        id: "pd-2",
        name: "Leather Wallet",
        description: "Premium leather wallet with RFID protection.",
        category: "Accessories",
        sub_category: "Wallets",
        item_group: "Fashion",
        status: true,
    },
    {
        id: "pd-3",
        name: "Smartphone Case",
        description: "Shockproof smartphone case for durability.",
        category: "Electronics",
        sub_category: "Cases & Covers",
        item_group: "Mobile Accessories",
        status: false,
    },
    {
        id: "pd-4",
        name: "Bluetooth Headphones",
        description: "Noise-canceling wireless headphones.",
        category: "Electronics",
        sub_category: "Audio",
        item_group: "Gadgets",
        status: true,
    },
    {
        id: "pd-5",
        name: "Trekking Backpack",
        description: "Water-resistant backpack with multiple compartments.",
        category: "Bags",
        sub_category: "Backpacks",
        item_group: "Outdoor",
        status: true,
    },
    {
        id: "pd-6",
        name: "Yoga Mat",
        description: "Non-slip yoga mat with extra cushioning.",
        category: "Fitness",
        sub_category: "Mats",
        item_group: "Wellness",
        status: false,
    },
    {
        id: "pd-7",
        name: "Wireless Mouse",
        description: "Ergonomic wireless mouse with adjustable DPI.",
        category: "Computers",
        sub_category: "Accessories",
        item_group: "Peripherals",
        status: true,
    },
    {
        id: "pd-8",
        name: "Sunglasses",
        description: "UV protection sunglasses with polarized lenses.",
        category: "Accessories",
        sub_category: "Eyewear",
        item_group: "Fashion",
        status: true,
    },
    {
        id: "pd-9",
        name: "Digital Watch",
        description: "Waterproof smartwatch with fitness tracking.",
        category: "Electronics",
        sub_category: "Wearables",
        item_group: "Gadgets",
        status: false,
    },
    {
        id: "pd-10",
        name: "Cotton T-Shirt",
        description: "Breathable cotton t-shirt for casual wear.",
        category: "Clothing",
        sub_category: "T-Shirts",
        item_group: "Apparel",
        status: true,
    },
];


export const mockProductDetails: ProductDetailDto = {
    id: "pdd-001",
    code: "PRD001",
    name: "Organic Green Tea",
    status: true,
    description: "Premium organic green tea with a rich aroma.",
    local_description: "ชาเขียวออร์แกนิกคุณภาพสูง",
    category: "Beverages",
    sub_category: "Tea",
    item_group: "Organic",
    unit: "Box",
    usage_ingredient: true,
    attributes: [
        { name: "Origin", value: "Japan" },
        { name: "Type", value: "Loose Leaf" },
    ],
    price_info: [
        { name: "Retail Price", value: "10.99" },
        { name: "Wholesale Price", value: "8.99" },
    ],
    order_unit: [
        { name: "Box", description: "A pack of 10 tea bags", conversion_factor: 10, default: true },
        { name: "Carton", description: "A pack of 12 boxes", conversion_factor: 120, default: false },
    ],
    ingredients_unit: [
        { unit: "Gram", description: "Measured in grams", conversion_factor: 1, default: true },
    ],
    stock_count: [
        { unit: "Box", description: "Stock counted in boxes", conversion_factor: 10, default: true },
        { unit: "Carton", description: "Stock counted in cartons", conversion_factor: 120, default: false },
    ],
};

