import {
  JournalEntriesDto,
  StockMovementDto,
  StoreRequisitionDetailDto,
  StoreRequisitionDto,
  StoreRequisitionItemDto,
} from "@/dtos/store-operation.dto";

export const mockStoreRequisitions: StoreRequisitionDto[] = [
  {
    id: "SR-001",
    ref_no: "REQ-20240301-001",
    request_to: "Main Warehouse",
    store_name: "Office Supplies",
    description: "Request for printing paper and stationery",
    total_amount: 1200,
    status: "Pending",
    date_created: "2024-03-01",
  },
  {
    id: "SR-002",
    ref_no: "REQ-20240302-002",
    request_to: "IT Storage",
    store_name: "IT Equipment",
    description: "Request for replacement keyboards and mice",
    total_amount: 4500,
    status: "Approved",
    date_created: "2024-03-02",
  },
  {
    id: "SR-003",
    ref_no: "REQ-20240303-003",
    request_to: "Marketing Storage",
    store_name: "Marketing Materials",
    description: "Request for promotional banners and flyers",
    total_amount: 3200,
    status: "Under Review",
    date_created: "2024-03-03",
  },
  {
    id: "SR-004",
    ref_no: "REQ-20240304-004",
    request_to: "HR Supplies",
    store_name: "HR Department",
    description: "Request for onboarding kits for new employees",
    total_amount: 2500,
    status: "Rejected",
    date_created: "2024-03-04",
  },
  {
    id: "SR-005",
    ref_no: "REQ-20240305-005",
    request_to: "Facilities Storage",
    store_name: "Building Maintenance",
    description: "Request for new light bulbs and cleaning supplies",
    total_amount: 1800,
    status: "Approved",
    date_created: "2024-03-05",
  },
  {
    id: "SR-006",
    ref_no: "REQ-20240306-006",
    request_to: "Medical Supplies",
    store_name: "Health & Safety",
    description: "Request for first aid kits and safety gloves",
    total_amount: 5000,
    status: "Pending",
    date_created: "2024-03-06",
  },
  {
    id: "SR-007",
    ref_no: "REQ-20240307-007",
    request_to: "IT Storage",
    store_name: "Software Licenses",
    description: "Request for additional Microsoft Office licenses",
    total_amount: 15000,
    status: "Completed",
    date_created: "2024-03-07",
  },
  {
    id: "SR-008",
    ref_no: "REQ-20240308-008",
    request_to: "Main Warehouse",
    store_name: "Office Furniture",
    description: "Request for ergonomic chairs and desks",
    total_amount: 20000,
    status: "Under Review",
    date_created: "2024-03-08",
  },
  {
    id: "SR-009",
    ref_no: "REQ-20240309-009",
    request_to: "Security Storage",
    store_name: "Security Equipment",
    description: "Request for new CCTV cameras and alarm system parts",
    total_amount: 18000,
    status: "Rejected",
    date_created: "2024-03-09",
  },
  {
    id: "SR-010",
    ref_no: "REQ-20240310-010",
    request_to: "HR Supplies",
    store_name: "Training Materials",
    description: "Request for training manuals and printed handouts",
    total_amount: 6000,
    status: "Completed",
    date_created: "2024-03-10",
  },
];

export const mockStockData = [
  {
    id: 1,
    name: "Thai Milk Tea",
    description: "Premium Thai tea powder with creamer (12 sachets/box)",
    sku: "BEV-001",
    location: "Central Kitchen",
    locationCode: "CK-001",
    currentStock: 25,
    minLevel: 30,
    maxLevel: 100,
    parLevel: 80,
    onOrder: 50,
    reorderPoint: 40,
    lastPrice: 45.99,
    lastVendor: "Thai Beverage Co.",
    status: "low",
    usage: "high",
    orderAmount: 0,
    unit: "Box",
  },
  {
    id: 2,
    name: "Coffee Beans",
    description: "Premium Arabica whole beans (1kg/bag)",
    sku: "BEV-002",
    location: "Roastery Store",
    locationCode: "RS-001",
    currentStock: 45,
    minLevel: 20,
    maxLevel: 80,
    parLevel: 60,
    onOrder: 0,
    reorderPoint: 30,
    lastPrice: 28.5,
    lastVendor: "Global Coffee Suppliers",
    status: "normal",
    usage: "medium",
    orderAmount: 0,
    unit: "Bag",
  },
];

export const mockStockLevels = [
  { month: "Jan", level: 150 },
  { month: "Feb", level: 180 },
  { month: "Mar", level: 120 },
  { month: "Apr", level: 200 },
  { month: "May", level: 160 },
  { month: "Jun", level: 140 },
];

export const mockMonthlyWastage = [
  { month: "Jan", value: 2500 },
  { month: "Feb", value: 1800 },
  { month: "Mar", value: 3200 },
  { month: "Apr", value: 2200 },
  { month: "May", value: 2800 },
  { month: "Jun", value: 1900 },
];

export const mockWastageByReason = [
  { name: "Expiration", value: 45 },
  { name: "Damage", value: 25 },
  { name: "Quality Issues", value: 20 },
  { name: "Other", value: 10 },
];

export const mockWastageRecords = [
  {
    id: 1,
    date: "2024-01-15",
    itemCode: "BEV-001",
    itemName: "Thai Milk Tea (12 pack)",
    quantity: 5,
    unitCost: 45.99,
    totalLoss: 229.95,
    reason: "Expiration",
    reportedBy: "John Smith",
    status: "Pending Review",
  },
  {
    id: 2,
    date: "2024-01-14",
    itemCode: "BEV-002",
    itemName: "Coffee Beans (1kg)",
    quantity: 2,
    unitCost: 28.5,
    totalLoss: 57.0,
    reason: "Quality Issues",
    reportedBy: "Jane Doe",
    status: "Approved",
  },
];

export const mockStoreRequisitionId: StoreRequisitionDetailDto = {
  id: "SR-001",
  ref_no: "REQ-20240301-001",
  item_name: "Thai Milk Tea",
  status: "Pending",
  date: "2024-03-01",
  expected_delivery_date: "2024-03-05",
  dp_req_from: "Main Store",
  job_code: "JOB-20240301-001",
  dp_req_to: "Marketing Store",
  description: "Request for Thai Milk Tea",
};

export const mockStoreRequisitionItems: StoreRequisitionItemDto[] = [
  {
    id: "SR-001-001",
    name: "Kitchen",
    location_code: "CK-001",
    inventory_type: "Direct",
    unit: "Box",
    required_qty: 10,
    approved_qty: 0,
    issued_qty: 0,
    total_amount: 459.9,
    status: "Pending",
    product_name: "Thai Milk Tea",
  },
  {
    id: "SR-001-002",
    name: "Bathroom",
    location_code: "CK-002",
    inventory_type: "Direct",
    unit: "Pack",
    required_qty: 5,
    approved_qty: 0,
    issued_qty: 0,
    total_amount: 129.5,
    status: "Pending",
    product_name: "Soft Drinks",
  },
  {
    id: "SR-001-003",
    name: "Living Room",
    location_code: "CK-003",
    inventory_type: "Indirect",
    unit: "Set",
    required_qty: 2,
    approved_qty: 0,
    issued_qty: 0,
    total_amount: 890.0,
    status: "Pending",
    product_name: "Sofa",
  },
  {
    id: "SR-001-004",
    name: "Office Supplies",
    location_code: "CK-004",
    inventory_type: "Direct",
    unit: "Piece",
    required_qty: 50,
    approved_qty: 0,
    issued_qty: 0,
    total_amount: 250.75,
    status: "Pending",
    product_name: "Pen",
  },
  {
    id: "SR-001-005",
    name: "Cleaning Tools",
    location_code: "CK-005",
    inventory_type: "Indirect",
    unit: "Box",
    required_qty: 8,
    approved_qty: 0,
    issued_qty: 0,
    total_amount: 315.6,
    status: "Pending",
    product_name: "Ped Pro สีม่วง",
  },
];

export const mockStockMovement: StockMovementDto[] = [
  {
    id: "SM-001",
    code: "SM-2024-001",
    location: "Roastery Store",
    location_code: "RS-001",
    product_name: "Premium Coffee Beans",
    lot_no: "LOT-2024-01-15-002",
    unit: "Bag",
    stock_in: 10,
    stock_out: 0,
    unit_cost: 28.5,
    total_cost: 285.0,
  },
  {
    id: "SM-002",
    code: "SM-2024-002",
    location: "Main Warehouse",
    location_code: "MW-001",
    product_name: "Espresso Machine Cleaner",
    lot_no: "LOT-2024-01-20-001",
    unit: "Bottle",
    stock_in: 0,
    stock_out: 5,
    unit_cost: 15.0,
    total_cost: 75.0,
  },
  {
    id: "SM-003",
    code: "SM-2024-003",
    location: "Branch Store A",
    location_code: "BS-A01",
    product_name: "Milk Frother",
    lot_no: "LOT-2024-02-05-004",
    unit: "Piece",
    stock_in: 3,
    stock_out: 0,
    unit_cost: 45.0,
    total_cost: 135.0,
  },
  {
    id: "SM-004",
    code: "SM-2024-004",
    location: "Roastery Store",
    location_code: "RS-001",
    product_name: "Arabica Beans",
    lot_no: "LOT-2024-01-25-003",
    unit: "Bag",
    stock_in: 0,
    stock_out: 8,
    unit_cost: 26.75,
    total_cost: 214.0,
  },
  {
    id: "SM-005",
    code: "SM-2024-005",
    location: "Main Warehouse",
    location_code: "MW-001",
    product_name: "Coffee Filters",
    lot_no: "LOT-2024-02-01-006",
    unit: "Pack",
    stock_in: 20,
    stock_out: 0,
    unit_cost: 3.25,
    total_cost: 65.0,
  },
];

export const mockJournalEntries: JournalEntriesDto = {
  id: "aasf98q2ed",
  je_code: "JE-2024-001",
  doc_type: "Store Requisition",
  transaction_date: "2024-01-15",
  status: "Pending",
  je_ref_no: "JV-222",
  total_amount: 459.9,
  source: "Store Requisition",
  description: "Monthly supplies request",
  ie_items: [
    {
      id: "zczw3asdad",
      account_name: "Inventory - Raw Materials",
      dp_name: "Main Warehouse",
      dp_code: "MW-001",
      description: "Monthly supplies request",
      debit: 459.9,
      credit: 0,
    },
    {
      id: "sd12312asx",
      account_name: "Expense - Maintenance",
      dp_name: "Roastery Store",
      dp_code: "RS-001",
      description: "Machine cleaning service",
      debit: 150.0,
      credit: 0,
    },
    {
      id: "qwop456zxc",
      account_name: "Inventory - Finished Goods",
      dp_name: "Branch Store A",
      dp_code: "BS-A01",
      description: "Stock transfer to branch",
      debit: 0,
      credit: 320.0,
    },
    {
      id: "asdzx4531qw",
      account_name: "Expense - Utilities",
      dp_name: "Head Office",
      dp_code: "HO-001",
      description: "Electricity bill for January",
      debit: 200.0,
      credit: 0,
    },
    {
      id: "vbnm9012qwe",
      account_name: "Inventory - Packaging",
      dp_name: "Packaging Unit",
      dp_code: "PU-002",
      description: "New packaging materials",
      debit: 89.5,
      credit: 0,
    },
  ],
};
