import { UserDto } from "@/dtos/um.dto";

export const mockUsers: UserDto[] = [
    {
        id: "um-001",
        name: "John Doe",
        email: "john.doe@example.com",
        businessUnit: "Business Unit 1",
        department: "Department 1",
        status: true,
        lastLogin: "2024-03-01",
    },
    {
        id: "um-002",
        name: "田中 弘 (Hiroshi Tanaka)",
        email: "hiroshi.tanaka@example.jp",
        businessUnit: "Business Unit 2",
        department: "Department 2",
        status: false,
        lastLogin: "2024-02-28",
    },
    {
        id: "um-003",
        name: "Pierre Dubois",
        email: "pierre.dubois@example.fr",
        businessUnit: "Business Unit 3",
        department: "Department 1",
        status: true,
        lastLogin: "2024-03-02",
    },
    {
        id: "um-004",
        name: "María González",
        email: "maria.gonzalez@example.es",
        businessUnit: "Business Unit 4",
        department: "Department 3",
        status: true,
        lastLogin: "2024-03-03",
    },
    {
        id: "um-005",
        name: "李伟 (Li Wei)",
        email: "li.wei@example.cn",
        businessUnit: "Business Unit 5",
        department: "Department 4",
        status: true,
        lastLogin: "2024-03-04",
    },
    {
        id: "um-006",
        name: "Hans Müller",
        email: "hans.muller@example.de",
        businessUnit: "Business Unit 6",
        department: "Department 5",
        status: false,
        lastLogin: "2024-03-05",
    },
    {
        id: "um-007",
        name: "Иван Смирнов (Ivan Smirnov)",
        email: "ivan.smirnov@example.ru",
        businessUnit: "Business Unit 7",
        department: "Department 6",
        status: true,
        lastLogin: "2024-03-06",
    },
    {
        id: "um-008",
        name: "Giuseppe Rossi",
        email: "giuseppe.rossi@example.it",
        businessUnit: "Business Unit 8",
        department: "Department 7",
        status: true,
        lastLogin: "2024-03-07",
    },
    {
        id: "um-009",
        name: "김민준 (Minjun Kim)",
        email: "minjun.kim@example.kr",
        businessUnit: "Business Unit 9",
        department: "Department 8",
        status: false,
        lastLogin: "2024-03-08",
    },
    {
        id: "um-010",
        name: "อภิชาติ วงศ์สุวรรณ (Apichat Wongsuwan)",
        email: "apichat.w@example.th",
        businessUnit: "Business Unit 10",
        department: "Department 9",
        status: true,
        lastLogin: "2024-03-09",
    }
];


