import { VendorGetDto } from "@/dtos/vendor-management";

export const mockVendors: VendorGetDto[] = [
  {
    id: "vendor-001",
    code: "V-001",
    note: null,
    tax_profile_id: null,
    tax_profile_name: null,
    tax_rate: null,
    dimension: {},
    name: "ABC Industrial Supplies",
    description: "Industrial supplies and equipment",
    business_type: [{ id: "bt-001", name: "Industrial Supplier" }],
    info: [
      { label: "Email", value: "contact@abc-supplies.com", data_type: "string" },
      { label: "Phone", value: "+66 2 123 4567", data_type: "string" },
      { label: "Tax ID", value: "0105558123456", data_type: "string" },
    ],
    is_active: true,
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2024-01-15T08:00:00Z",
    vendor_address: [
      {
        id: "addr-001",
        address_type: "contact_address",
        data: {
          address_line1: "123 Industrial Road",
          district: "Bangkok",
          province: "Bangkok",
          country: "Thailand",
        },
        is_active: true,
      },
    ],
    vendor_contact: [
      {
        name: "John Smith",
        email: "john@abc-supplies.com",
        phone: "+66 81 234 5678",
        is_primary: true,
      },
    ],
  },
  {
    id: "vendor-002",
    code: "V-002",
    note: null,
    tax_profile_id: null,
    tax_profile_name: null,
    tax_rate: null,
    dimension: {},
    name: "Global Tech Solutions",
    description: "Technology solutions and services",
    business_type: [{ id: "bt-002", name: "Technology Provider" }],
    info: [
      { label: "Email", value: "info@globaltech.com", data_type: "string" },
      { label: "Phone", value: "+66 2 234 5678", data_type: "string" },
      { label: "Tax ID", value: "0105559234567", data_type: "string" },
    ],
    is_active: true,
    created_at: "2024-01-20T09:00:00Z",
    updated_at: "2024-01-20T09:00:00Z",
    vendor_address: [
      {
        id: "addr-002",
        address_type: "contact_address",
        data: {
          address_line1: "456 Technology Plaza",
          district: "Bangkok",
          province: "Bangkok",
          country: "Thailand",
        },
        is_active: true,
      },
    ],
    vendor_contact: [
      {
        name: "Jane Doe",
        email: "jane@globaltech.com",
        phone: "+66 81 345 6789",
        is_primary: true,
      },
    ],
  },
  {
    id: "vendor-003",
    code: "V-003",
    note: null,
    tax_profile_id: null,
    tax_profile_name: null,
    tax_rate: null,
    dimension: {},
    name: "Prime Manufacturing Co.",
    description: "Manufacturing and production",
    business_type: [{ id: "bt-003", name: "Manufacturer" }],
    info: [
      { label: "Email", value: "sales@primemfg.com", data_type: "string" },
      { label: "Phone", value: "+66 2 345 6789", data_type: "string" },
      { label: "Tax ID", value: "0105560345678", data_type: "string" },
    ],
    is_active: true,
    created_at: "2024-02-01T10:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
    vendor_address: [
      {
        id: "addr-003",
        address_type: "contact_address",
        data: {
          address_line1: "789 Manufacturing Ave",
          district: "Samut Prakan",
          province: "Samut Prakan",
          country: "Thailand",
        },
        is_active: true,
      },
    ],
    vendor_contact: [
      {
        name: "Bob Johnson",
        email: "bob@primemfg.com",
        phone: "+66 81 456 7890",
        is_primary: true,
      },
    ],
  },
  {
    id: "vendor-004",
    code: "V-004",
    note: null,
    tax_profile_id: null,
    tax_profile_name: null,
    tax_rate: null,
    dimension: {},
    name: "Eastern Logistics Ltd.",
    description: "Logistics and transportation",
    business_type: [{ id: "bt-004", name: "Logistics" }],
    info: [
      { label: "Email", value: "contact@easternlogistics.com", data_type: "string" },
      { label: "Phone", value: "+66 2 456 7890", data_type: "string" },
      { label: "Tax ID", value: "0105561456789", data_type: "string" },
    ],
    is_active: true,
    created_at: "2024-02-10T11:00:00Z",
    updated_at: "2024-02-10T11:00:00Z",
    vendor_address: [
      {
        id: "addr-004",
        address_type: "contact_address",
        data: {
          address_line1: "321 Logistics Center",
          district: "Chonburi",
          province: "Chonburi",
          country: "Thailand",
        },
        is_active: true,
      },
    ],
    vendor_contact: [
      {
        name: "Alice Wong",
        email: "alice@easternlogistics.com",
        phone: "+66 81 567 8901",
        is_primary: true,
      },
    ],
  },
  {
    id: "vendor-005",
    code: "V-005",
    note: null,
    tax_profile_id: null,
    tax_profile_name: null,
    tax_rate: null,
    dimension: {},
    name: "Quality Parts International",
    description: "Parts and components supplier",
    business_type: [{ id: "bt-005", name: "Parts Supplier" }],
    info: [
      { label: "Email", value: "info@qualityparts.com", data_type: "string" },
      { label: "Phone", value: "+66 2 567 8901", data_type: "string" },
      { label: "Tax ID", value: "0105562567890", data_type: "string" },
    ],
    is_active: true,
    created_at: "2024-02-15T12:00:00Z",
    updated_at: "2024-02-15T12:00:00Z",
    vendor_address: [
      {
        id: "addr-005",
        address_type: "contact_address",
        data: {
          address_line1: "654 Parts Boulevard",
          district: "Bangkok",
          province: "Bangkok",
          country: "Thailand",
        },
        is_active: true,
      },
    ],
    vendor_contact: [
      {
        name: "Michael Chen",
        email: "michael@qualityparts.com",
        phone: "+66 81 678 9012",
        is_primary: true,
      },
    ],
  },
  {
    id: "vendor-006",
    code: "V-006",
    note: null,
    tax_profile_id: null,
    tax_profile_name: null,
    tax_rate: null,
    dimension: {},
    name: "Superior Equipment Corp.",
    description: "Equipment and machinery",
    business_type: [{ id: "bt-006", name: "Equipment Supplier" }],
    info: [
      { label: "Email", value: "sales@superiorequip.com", data_type: "string" },
      { label: "Phone", value: "+66 2 678 9012", data_type: "string" },
      { label: "Tax ID", value: "0105563678901", data_type: "string" },
    ],
    is_active: true,
    created_at: "2024-03-01T13:00:00Z",
    updated_at: "2024-03-01T13:00:00Z",
    vendor_address: [
      {
        id: "addr-006",
        address_type: "contact_address",
        data: {
          address_line1: "987 Equipment Road",
          district: "Rayong",
          province: "Rayong",
          country: "Thailand",
        },
        is_active: true,
      },
    ],
    vendor_contact: [
      {
        name: "Sarah Lee",
        email: "sarah@superiorequip.com",
        phone: "+66 81 789 0123",
        is_primary: true,
      },
    ],
  },
];

export const mockVendorsResponse = {
  data: mockVendors,
  total: mockVendors.length,
  page: 1,
  pageSize: 10,
};
