import { PriceListDto, VendorDto } from "@/dtos/vendor-management";

export const mockVendorData: VendorDto[] = [
    {
        id: "VND-001",
        name: "株式会社テクノロジーソリューションズ",
        bu_type: "ITサービス",
        address: "東京都千代田区丸の内1-1-1, 日本",
        contact_person: {
            name: "佐藤 健",
            phone: "+81-3-1234-5678",
            email: "sato@techsolutions.jp",
        },
    },
    {
        id: "VND-002",
        name: "绿能科技有限公司",
        bu_type: "可再生能源",
        address: "北京市朝阳区长安街100号, 中国",
        contact_person: {
            name: "王 伟",
            phone: "+86-10-9876-5432",
            email: "wangwei@greenenergy.cn",
        },
    },
    {
        id: "VND-003",
        name: "Global Logística Ltda.",
        bu_type: "Logística",
        address: "Avenida Paulista, 2000, São Paulo, Brasil",
        contact_person: {
            name: "Carlos Eduardo",
            phone: "+55-11-99876-5432",
            email: "carlos@globallogistica.com.br",
        },
    },
    {
        id: "VND-004",
        name: "Société Française de Construction",
        bu_type: "Construction",
        address: "10 Rue de la Paix, Paris, France",
        contact_person: {
            name: "Jean Dupont",
            phone: "+33-1-2345-6789",
            email: "jean.dupont@construction.fr",
        },
    },
    {
        id: "VND-005",
        name: "شركة الأطعمة الصحية",
        bu_type: "الأغذية والمشروبات",
        address: "شارع الملك فهد، الرياض، المملكة العربية السعودية",
        contact_person: {
            name: "أحمد الجابر",
            phone: "+966-50-123-4567",
            email: "ahmed@healthyfoods.sa",
        },
    },
    {
        id: "VND-006",
        name: "Глобал Транспорт",
        bu_type: "Логистика",
        address: "Ленинградский проспект, Москва, Россия",
        contact_person: {
            name: "Алексей Иванов",
            phone: "+7-495-123-4567",
            email: "ivanov@globaltrans.ru",
        },
    },
    {
        id: "VND-007",
        name: "Krüger Maschinenbau GmbH",
        bu_type: "Maschinenbau",
        address: "Berliner Straße 10, Berlin, Deutschland",
        contact_person: {
            name: "Hans Krüger",
            phone: "+49-30-9876-5432",
            email: "hans.krueger@maschinenbau.de",
        },
    },
    {
        id: "VND-008",
        name: "NextGen Pharma Pvt. Ltd.",
        bu_type: "Pharmaceuticals",
        address: "Mahatma Gandhi Road, Mumbai, India",
        contact_person: {
            name: "Priya Sharma",
            phone: "+91-22-5678-9101",
            email: "priya.sharma@nextgenpharma.in",
        },
    },
    {
        id: "VND-009",
        name: "Soluciones Digitales S.A.",
        bu_type: "Publicidad",
        address: "Calle Gran Vía, Madrid, España",
        contact_person: {
            name: "Javier Martínez",
            phone: "+34-91-876-5432",
            email: "javier.martinez@digitales.es",
        },
    },
    {
        id: "VND-010",
        name: "บริษัท สมาร์ทโฮม เทคโนโลยี จำกัด",
        bu_type: "เทคโนโลยีบ้านอัจฉริยะ",
        address: "ถนนพระราม 9, กรุงเทพฯ, ประเทศไทย",
        contact_person: {
            name: "สมชาย วัฒนาพงษ์",
            phone: "+66-2-345-6789",
            email: "somchai@smarthome.co.th",
        },
    },
];

export const mockPriceListData: PriceListDto[] = [
    {
        id: "PL-001",
        name: "テクノロジー プロモーション",
        code: "JP-TECH-2024",
        description: "最新の技術製品の割引",
        status: true,
        start_date: "2024-04-01",
        end_date: "2024-06-30",
    },
    {
        id: "PL-002",
        name: "绿色能源优惠",
        code: "CN-ENERGY-2024",
        description: "可再生能源产品的特价促销",
        status: true,
        start_date: "2024-05-01",
        end_date: "2024-07-31",
    },
    {
        id: "PL-003",
        name: "Promoção de Eletrônicos",
        code: "BR-ELEC-2024",
        description: "Grandes descontos em eletrônicos",
        status: true,
        start_date: "2024-06-01",
        end_date: "2024-08-31",
    },
    {
        id: "PL-004",
        name: "Offre Spéciale Construction",
        code: "FR-CONST-2024",
        description: "Réduction sur les matériaux de construction",
        status: false,
        start_date: "2024-07-01",
        end_date: "2024-09-30",
    },
    {
        id: "PL-005",
        name: "خصومات الأغذية الصحية",
        code: "SA-FOOD-2024",
        description: "عروض خاصة على الأغذية العضوية",
        status: true,
        start_date: "2024-08-01",
        end_date: "2024-10-31",
    },
    {
        id: "PL-006",
        name: "Скидки на транспортные услуги",
        code: "RU-TRANS-2024",
        description: "Сезонные скидки на логистику",
        status: true,
        start_date: "2024-09-01",
        end_date: "2024-11-30",
    },
    {
        id: "PL-007",
        name: "Sonderangebot Maschinenbau",
        code: "DE-MACHINE-2024",
        description: "Rabatte auf Industriemaschinen",
        status: false,
        start_date: "2024-10-01",
        end_date: "2024-12-31",
    },
    {
        id: "PL-008",
        name: "फार्मास्यूटिकल ऑफर",
        code: "IN-PHARMA-2024",
        description: "स्वास्थ्य उत्पादों पर विशेष छूट",
        status: true,
        start_date: "2024-11-01",
        end_date: "2025-01-31",
    },
    {
        id: "PL-009",
        name: "Oferta de Publicidad Digital",
        code: "ES-ADS-2024",
        description: "Descuentos en publicidad online",
        status: true,
        start_date: "2024-12-01",
        end_date: "2025-02-28",
    },
    {
        id: "PL-010",
        name: "โปรโมชั่นสินค้าเทคโนโลยี",
        code: "TH-TECH-2024",
        description: "ลดราคาพิเศษสำหรับสินค้าไอที",
        status: false,
        start_date: "2025-01-01",
        end_date: "2025-03-31",
    },
];
